### ISSUE TITLE
Home Assistant 2025.1

### ISSUE THREAD

**Issue by norimicry** [community-scripts/ProxmoxVE#1218]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

Home Assistant Core LXC

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/homeassistant-core.sh)"

### 📝 Provide a clear and concise description of the issue.

The script is installing Home Assistant 2024.12.5 but 2025.1 has recently been released. Is this something that needs to be resolved upstream or within the script itself? The Home Assistant VM is able to be updated to 2025.1.

### ⚙️ What settings are you using?

- [X] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Ubuntu 24.04

### 🔄 Steps to reproduce the issue.

Step 1: Install Home Assistant Core LXC
Step 2: Navigate to HA dashboard
Step 3: Click Settings
Step 4: Click About

### ❌ Paste the full error output (if available).

N/A

**Comment by norimicry** [comment]
In the upstream HA Core [pyproject.toml](https://github.com/home-assistant/core/blob/dev/pyproject.toml), I do see the version listed as `version = "2025.2.0.dev0"`.

**Comment by MickLesk** [comment]
can you try:

pip install homeassistant==2025.1.0

**Comment by norimicry** [comment]
It did appear to install, however, the UI was still showing the previous version on reload/reboot. In an attempt to start fresh, I reran the script again, thinking I may have just been ahead of the release and upstream dependencies and am now receiving 

```
Note, selecting 'python3-pip' instead of 'pip'
 ⠹E: Unable to locate package python3.13-dev
E: Couldn't find any package by glob 'python3.13-dev'
E: Couldn't find any package by regex 'python3.13-dev'

[ERROR] in line 17: exit code 0: while executing command $STD apt-get install -y git curl sudo mc bluez libffi-dev libssl-dev libjpeg-dev zlib1g-dev autoconf build-essential libopenjp2-7 libturbojpeg0-dev ffmpeg liblapack3 liblapack-dev dbus-broker libpcap-dev libavdevice-dev libavformat-dev libavcodec-dev libavutil-dev libavfilter-dev libmariadb-dev-compat libatlas-base-dev pip python3.13-dev
```

**Comment by MickLesk** [comment]
Fixed. Funny, HomeAssistant need 3.13, but 3.13 is not in default repo :-D Trolls

**Comment by norimicry** [comment]
Thanks for fixing the Python issue so quickly! However, reinstalling the LXC via script is still resulting in HA 2024, not 2025.

`pip install homeassistant==2025.1.0`:

```
root@homeassistant-core:~# pip install homeassistant==2025.1.0
Collecting homeassistant==2025.1.0
  Downloading homeassistant-2025.1.0-py3-none-any.whl.metadata (4.8 kB)
Collecting aiodns==3.2.0 (from homeassistant==2025.1.0)
  Downloading aiodns-3.2.0-py3-none-any.whl.metadata (4.0 kB)
Collecting aiohasupervisor==0.2.2b5 (from homeassistant==2025.1.0)
  Downloading aiohasupervisor-0.2.2b5-py3-none-any.whl.metadata (5.1 kB)
Collecting aiohttp==3.11.11 (from homeassistant==2025.1.0)
  Downloading aiohttp-3.11.11-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.7 kB)
Collecting aiohttp-cors==0.7.0 (from homeassistant==2025.1.0)
  Downloading aiohttp_cors-0.7.0-py3-none-any.whl.metadata (20 kB)
Collecting aiohttp-fast-zlib==0.2.0 (from homeassistant==2025.1.0)
  Downloading aiohttp_fast_zlib-0.2.0-py3-none-any.whl.metadata (5.6 kB)
Collecting aiozoneinfo==0.2.1 (from homeassistant==2025.1.0)
  Downloading aiozoneinfo-0.2.1-py3-none-any.whl.metadata (5.5 kB)
Collecting astral==2.2 (from homeassistant==2025.1.0)
  Downloading astral-2.2-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting async-interrupt==1.2.0 (from homeassistant==2025.1.0)
  Downloading async_interrupt-1.2.0-py3-none-any.whl.metadata (4.9 kB)
Collecting attrs==24.2.0 (from homeassistant==2025.1.0)
  Downloading attrs-24.2.0-py3-none-any.whl.metadata (11 kB)
Collecting atomicwrites-homeassistant==1.4.1 (from homeassistant==2025.1.0)
  Downloading atomicwrites_homeassistant-1.4.1-py2.py3-none-any.whl.metadata (6.0 kB)
Collecting awesomeversion==24.6.0 (from homeassistant==2025.1.0)
  Downloading awesomeversion-24.6.0-py3-none-any.whl.metadata (9.0 kB)
Collecting bcrypt==4.2.0 (from homeassistant==2025.1.0)
  Downloading bcrypt-4.2.0-cp39-abi3-manylinux_2_28_x86_64.whl.metadata (9.6 kB)
Collecting certifi>=2021.5.30 (from homeassistant==2025.1.0)
  Downloading certifi-2024.12.14-py3-none-any.whl.metadata (2.3 kB)
Collecting ciso8601==2.3.2 (from homeassistant==2025.1.0)
  Downloading ciso8601-2.3.2-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (23 kB)
Collecting cronsim==2.6 (from homeassistant==2025.1.0)
  Downloading cronsim-2.6-py3-none-any.whl.metadata (6.9 kB)
Collecting fnv-hash-fast==1.0.2 (from homeassistant==2025.1.0)
  Downloading fnv_hash_fast-1.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux_2_5_x86_64.manylinux1_x86_64.manylinux2014_x86_64.whl.metadata (4.7 kB)
Collecting hass-nabucasa==0.87.0 (from homeassistant==2025.1.0)
  Downloading hass_nabucasa-0.87.0-py3-none-any.whl.metadata (1.8 kB)
Collecting httpx==0.27.2 (from homeassistant==2025.1.0)
  Downloading httpx-0.27.2-py3-none-any.whl.metadata (7.1 kB)
Collecting home-assistant-bluetooth==1.13.0 (from homeassistant==2025.1.0)
  Downloading home_assistant_bluetooth-1.13.0-py3-none-any.whl.metadata (5.4 kB)
Collecting ifaddr==0.2.0 (from homeassistant==2025.1.0)
  Downloading ifaddr-0.2.0-py3-none-any.whl.metadata (4.9 kB)
Collecting Jinja2==3.1.5 (from homeassistant==2025.1.0)
  Downloading jinja2-3.1.5-py3-none-any.whl.metadata (2.6 kB)
Collecting lru-dict==1.3.0 (from homeassistant==2025.1.0)
  Downloading lru_dict-1.3.0-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.5 kB)
Collecting PyJWT==2.10.1 (from homeassistant==2025.1.0)
  Downloading PyJWT-2.10.1-py3-none-any.whl.metadata (4.0 kB)
Collecting cryptography==44.0.0 (from homeassistant==2025.1.0)
  Downloading cryptography-44.0.0-cp39-abi3-manylinux_2_28_x86_64.whl.metadata (5.7 kB)
Collecting Pillow==11.0.0 (from homeassistant==2025.1.0)
  Downloading pillow-11.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (9.1 kB)
Collecting propcache==0.2.1 (from homeassistant==2025.1.0)
  Downloading propcache-0.2.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.2 kB)
Collecting pyOpenSSL==24.3.0 (from homeassistant==2025.1.0)
  Downloading pyOpenSSL-24.3.0-py3-none-any.whl.metadata (15 kB)
Collecting orjson==3.10.12 (from homeassistant==2025.1.0)
  Downloading orjson-3.10.12-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.8/41.8 kB 2.2 MB/s eta 0:00:00
Collecting packaging>=23.1 (from homeassistant==2025.1.0)
  Downloading packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Collecting psutil-home-assistant==0.0.1 (from homeassistant==2025.1.0)
  Downloading psutil_home_assistant-0.0.1-py3-none-any.whl.metadata (882 bytes)
Collecting python-slugify==8.0.4 (from homeassistant==2025.1.0)
  Downloading python_slugify-8.0.4-py2.py3-none-any.whl.metadata (8.5 kB)
Collecting PyYAML==6.0.2 (from homeassistant==2025.1.0)
  Downloading PyYAML-6.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting requests==2.32.3 (from homeassistant==2025.1.0)
  Downloading requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting securetar==2024.11.0 (from homeassistant==2025.1.0)
  Downloading securetar-2024.11.0-py3-none-any.whl.metadata (2.0 kB)
Collecting SQLAlchemy==2.0.36 (from homeassistant==2025.1.0)
  Downloading SQLAlchemy-2.0.36-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.7 kB)
Collecting typing-extensions<5.0,>=4.12.2 (from homeassistant==2025.1.0)
  Downloading typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting ulid-transform==1.0.2 (from homeassistant==2025.1.0)
  Downloading ulid_transform-1.0.2-cp312-cp312-manylinux_2_36_x86_64.whl.metadata (5.4 kB)
Collecting urllib3<2,>=1.26.5 (from homeassistant==2025.1.0)
  Downloading urllib3-1.26.20-py2.py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 kB 2.8 MB/s eta 0:00:00
Collecting uv==0.5.8 (from homeassistant==2025.1.0)
  Downloading uv-0.5.8-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Collecting voluptuous==0.15.2 (from homeassistant==2025.1.0)
  Downloading voluptuous-0.15.2-py3-none-any.whl.metadata (20 kB)
Collecting voluptuous-serialize==2.6.0 (from homeassistant==2025.1.0)
  Downloading voluptuous_serialize-2.6.0-py3-none-any.whl.metadata (316 bytes)
Collecting voluptuous-openapi==0.0.5 (from homeassistant==2025.1.0)
  Downloading voluptuous_openapi-0.0.5-py3-none-any.whl.metadata (325 bytes)
Collecting yarl==1.18.3 (from homeassistant==2025.1.0)
  Downloading yarl-1.18.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (69 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.2/69.2 kB 5.0 MB/s eta 0:00:00
Collecting webrtc-models==0.3.0 (from homeassistant==2025.1.0)
  Downloading webrtc_models-0.3.0-py3-none-any.whl.metadata (2.9 kB)
Collecting pycares>=4.0.0 (from aiodns==3.2.0->homeassistant==2025.1.0)
  Downloading pycares-4.5.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Collecting mashumaro<4.0,>=3.11 (from aiohasupervisor==0.2.2b5->homeassistant==2025.1.0)
  Downloading mashumaro-3.15-py3-none-any.whl.metadata (117 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.0/118.0 kB 6.2 MB/s eta 0:00:00
Collecting aiohappyeyeballs>=2.3.0 (from aiohttp==3.11.11->homeassistant==2025.1.0)
  Downloading aiohappyeyeballs-2.4.4-py3-none-any.whl.metadata (6.1 kB)
Collecting aiosignal>=1.1.2 (from aiohttp==3.11.11->homeassistant==2025.1.0)
  Downloading aiosignal-1.3.2-py2.py3-none-any.whl.metadata (3.8 kB)
Collecting frozenlist>=1.1.1 (from aiohttp==3.11.11->homeassistant==2025.1.0)
  Downloading frozenlist-1.5.0-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp==3.11.11->homeassistant==2025.1.0)
  Downloading multidict-6.1.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.0 kB)
Collecting tzdata>=2024.1 (from aiozoneinfo==0.2.1->homeassistant==2025.1.0)
  Downloading tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting pytz (from astral==2.2->homeassistant==2025.1.0)
  Downloading pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting cffi>=1.12 (from cryptography==44.0.0->homeassistant==2025.1.0)
  Downloading cffi-1.17.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting fnvhash<0.2.0,>=0.1.0 (from fnv-hash-fast==1.0.2->homeassistant==2025.1.0)
  Downloading fnvhash-0.1.0.tar.gz (1.9 kB)
  Preparing metadata (setup.py) ... done
Collecting acme==3.0.1 (from hass-nabucasa==0.87.0->homeassistant==2025.1.0)
  Downloading acme-3.0.1-py3-none-any.whl.metadata (1.4 kB)
Collecting pycognito==2024.5.1 (from hass-nabucasa==0.87.0->homeassistant==2025.1.0)
  Downloading pycognito-2024.5.1-py3-none-any.whl.metadata (24 kB)
Collecting snitun==0.39.1 (from hass-nabucasa==0.87.0->homeassistant==2025.1.0)
  Downloading snitun-0.39.1-py3-none-any.whl.metadata (4.5 kB)
Collecting habluetooth>=3.0 (from home-assistant-bluetooth==1.13.0->homeassistant==2025.1.0)
  Downloading habluetooth-3.6.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.2 kB)
Collecting anyio (from httpx==0.27.2->homeassistant==2025.1.0)
  Downloading anyio-4.7.0-py3-none-any.whl.metadata (4.7 kB)
Collecting httpcore==1.* (from httpx==0.27.2->homeassistant==2025.1.0)
  Downloading httpcore-1.0.7-py3-none-any.whl.metadata (21 kB)
Collecting idna (from httpx==0.27.2->homeassistant==2025.1.0)
  Downloading idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting sniffio (from httpx==0.27.2->homeassistant==2025.1.0)
  Downloading sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting MarkupSafe>=2.0 (from Jinja2==3.1.5->homeassistant==2025.1.0)
  Downloading MarkupSafe-3.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.0 kB)
Collecting psutil (from psutil-home-assistant==0.0.1->homeassistant==2025.1.0)
  Downloading psutil-6.1.1-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (22 kB)
Collecting text-unidecode>=1.3 (from python-slugify==8.0.4->homeassistant==2025.1.0)
  Downloading text_unidecode-1.3-py2.py3-none-any.whl.metadata (2.4 kB)
Collecting charset-normalizer<4,>=2 (from requests==2.32.3->homeassistant==2025.1.0)
  Downloading charset_normalizer-3.4.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (35 kB)
Collecting greenlet!=0.4.17 (from SQLAlchemy==2.0.36->homeassistant==2025.1.0)
  Downloading greenlet-3.1.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Collecting josepy<2,>=1.13.0 (from acme==3.0.1->hass-nabucasa==0.87.0->homeassistant==2025.1.0)
  Downloading josepy-1.14.0-py3-none-any.whl.metadata (1.8 kB)
Collecting pyrfc3339 (from acme==3.0.1->hass-nabucasa==0.87.0->homeassistant==2025.1.0)
  Downloading pyRFC3339-2.0.1-py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: setuptools>=41.6.0 in /usr/lib/python3/dist-packages (from acme==3.0.1->hass-nabucasa==0.87.0->homeassistant==2025.1.0) (68.1.2)
Collecting h11<0.15,>=0.13 (from httpcore==1.*->httpx==0.27.2->homeassistant==2025.1.0)
  Downloading h11-0.14.0-py3-none-any.whl.metadata (8.2 kB)
Collecting boto3>=1.10.49 (from pycognito==2024.5.1->hass-nabucasa==0.87.0->homeassistant==2025.1.0)
  Downloading boto3-1.35.92-py3-none-any.whl.metadata (6.7 kB)
Collecting envs>=1.3 (from pycognito==2024.5.1->hass-nabucasa==0.87.0->homeassistant==2025.1.0)
  Downloading envs-1.4-py3-none-any.whl.metadata (842 bytes)
Collecting async-timeout>=3.0.1 (from snitun==0.39.1->hass-nabucasa==0.87.0->homeassistant==2025.1.0)
  Downloading async_timeout-5.0.1-py3-none-any.whl.metadata (5.1 kB)
Collecting pycparser (from cffi>=1.12->cryptography==44.0.0->homeassistant==2025.1.0)
  Downloading pycparser-2.22-py3-none-any.whl.metadata (943 bytes)
Collecting bleak>=0.21.1 (from habluetooth>=3.0->home-assistant-bluetooth==1.13.0->homeassistant==2025.1.0)
  Downloading bleak-0.22.3-py3-none-any.whl.metadata (5.4 kB)
Collecting bleak-retry-connector>=3.3.0 (from habluetooth>=3.0->home-assistant-bluetooth==1.13.0->homeassistant==2025.1.0)
  Downloading bleak_retry_connector-3.6.0-py3-none-any.whl.metadata (5.1 kB)
Collecting bluetooth-adapters>=0.16.1 (from habluetooth>=3.0->home-assistant-bluetooth==1.13.0->homeassistant==2025.1.0)
  Downloading bluetooth_adapters-0.20.2-py3-none-any.whl.metadata (5.3 kB)
Collecting bluetooth-auto-recovery>=1.2.3 (from habluetooth>=3.0->home-assistant-bluetooth==1.13.0->homeassistant==2025.1.0)
  Downloading bluetooth_auto_recovery-1.4.2-py3-none-any.whl.metadata (5.5 kB)
Collecting bluetooth-data-tools>=1.16.0 (from habluetooth>=3.0->home-assistant-bluetooth==1.13.0->homeassistant==2025.1.0)
  Downloading bluetooth_data_tools-1.20.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.0 kB)
Collecting dbus-fast<3,>=1.83.0 (from bleak>=0.21.1->habluetooth>=3.0->home-assistant-bluetooth==1.13.0->homeassistant==2025.1.0)
  Downloading dbus_fast-2.24.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (10 kB)
Collecting aiooui>=0.1.1 (from bluetooth-adapters>=0.16.1->habluetooth>=3.0->home-assistant-bluetooth==1.13.0->homeassistant==2025.1.0)
  Downloading aiooui-0.1.7-py3-none-any.whl.metadata (3.8 kB)
Collecting uart-devices>=0.1.0 (from bluetooth-adapters>=0.16.1->habluetooth>=3.0->home-assistant-bluetooth==1.13.0->homeassistant==2025.1.0)
  Downloading uart_devices-0.1.0-py3-none-any.whl.metadata (4.9 kB)
Collecting usb-devices>=0.4.5 (from bluetooth-adapters>=0.16.1->habluetooth>=3.0->home-assistant-bluetooth==1.13.0->homeassistant==2025.1.0)
  Downloading usb_devices-0.4.5-py3-none-any.whl.metadata (5.3 kB)
Collecting PyRIC>=0.1.6.3 (from bluetooth-auto-recovery>=1.2.3->habluetooth>=3.0->home-assistant-bluetooth==1.13.0->homeassistant==2025.1.0)
  Downloading PyRIC-0.1.6.3.tar.gz (870 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 870.4/870.4 kB 23.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting btsocket>=0.2.0 (from bluetooth-auto-recovery>=1.2.3->habluetooth>=3.0->home-assistant-bluetooth==1.13.0->homeassistant==2025.1.0)
  Downloading btsocket-0.3.0-py2.py3-none-any.whl.metadata (7.0 kB)
Collecting botocore<1.36.0,>=1.35.92 (from boto3>=1.10.49->pycognito==2024.5.1->hass-nabucasa==0.87.0->homeassistant==2025.1.0)
  Downloading botocore-1.35.92-py3-none-any.whl.metadata (5.7 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3>=1.10.49->pycognito==2024.5.1->hass-nabucasa==0.87.0->homeassistant==2025.1.0)
  Downloading jmespath-1.0.1-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.11.0,>=0.10.0 (from boto3>=1.10.49->pycognito==2024.5.1->hass-nabucasa==0.87.0->homeassistant==2025.1.0)
  Downloading s3transfer-0.10.4-py3-none-any.whl.metadata (1.7 kB)
Collecting python-dateutil<3.0.0,>=2.1 (from botocore<1.36.0,>=1.35.92->boto3>=1.10.49->pycognito==2024.5.1->hass-nabucasa==0.87.0->homeassistant==2025.1.0)
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.36.0,>=1.35.92->boto3>=1.10.49->pycognito==2024.5.1->hass-nabucasa==0.87.0->homeassistant==2025.1.0) (1.16.0)
Downloading homeassistant-2025.1.0-py3-none-any.whl (39.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.7/39.7 MB 47.2 MB/s eta 0:00:00
Downloading aiodns-3.2.0-py3-none-any.whl (5.7 kB)
Downloading aiohasupervisor-0.2.2b5-py3-none-any.whl (36 kB)
Downloading aiohttp-3.11.11-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 56.2 MB/s eta 0:00:00
Downloading aiohttp_cors-0.7.0-py3-none-any.whl (27 kB)
Downloading aiohttp_fast_zlib-0.2.0-py3-none-any.whl (8.4 kB)
Downloading aiozoneinfo-0.2.1-py3-none-any.whl (8.0 kB)
Downloading astral-2.2-py2.py3-none-any.whl (30 kB)
Downloading async_interrupt-1.2.0-py3-none-any.whl (8.9 kB)
Downloading atomicwrites_homeassistant-1.4.1-py2.py3-none-any.whl (7.1 kB)
Downloading attrs-24.2.0-py3-none-any.whl (63 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.0/63.0 kB 4.4 MB/s eta 0:00:00
Downloading awesomeversion-24.6.0-py3-none-any.whl (14 kB)
Downloading bcrypt-4.2.0-cp39-abi3-manylinux_2_28_x86_64.whl (273 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 273.8/273.8 kB 19.5 MB/s eta 0:00:00
Downloading ciso8601-2.3.2-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (40 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.1/40.1 kB 2.6 MB/s eta 0:00:00
Downloading cronsim-2.6-py3-none-any.whl (13 kB)
Downloading cryptography-44.0.0-cp39-abi3-manylinux_2_28_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 9.8 MB/s eta 0:00:00
Downloading fnv_hash_fast-1.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux_2_5_x86_64.manylinux1_x86_64.manylinux2014_x86_64.whl (154 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.2/154.2 kB 11.6 MB/s eta 0:00:00
Downloading hass_nabucasa-0.87.0-py3-none-any.whl (56 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.2/56.2 kB 3.7 MB/s eta 0:00:00
Downloading home_assistant_bluetooth-1.13.0-py3-none-any.whl (7.9 kB)
Downloading httpx-0.27.2-py3-none-any.whl (76 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.4/76.4 kB 5.5 MB/s eta 0:00:00
Downloading ifaddr-0.2.0-py3-none-any.whl (12 kB)
Downloading jinja2-3.1.5-py3-none-any.whl (134 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.6/134.6 kB 10.1 MB/s eta 0:00:00
Downloading lru_dict-1.3.0-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (32 kB)
Downloading orjson-3.10.12-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (131 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.6/131.6 kB 9.2 MB/s eta 0:00:00
Downloading pillow-11.0.0-cp312-cp312-manylinux_2_28_x86_64.whl (4.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.4/4.4 MB 55.2 MB/s eta 0:00:00
Downloading propcache-0.2.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (243 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 243.6/243.6 kB 12.9 MB/s eta 0:00:00
Downloading psutil_home_assistant-0.0.1-py3-none-any.whl (6.3 kB)
Downloading PyJWT-2.10.1-py3-none-any.whl (22 kB)
Downloading pyOpenSSL-24.3.0-py3-none-any.whl (56 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.1/56.1 kB 3.8 MB/s eta 0:00:00
Downloading python_slugify-8.0.4-py2.py3-none-any.whl (10 kB)
Downloading PyYAML-6.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (767 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 767.5/767.5 kB 32.1 MB/s eta 0:00:00
Downloading requests-2.32.3-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 4.5 MB/s eta 0:00:00
Downloading securetar-2024.11.0-py3-none-any.whl (9.4 kB)
Downloading SQLAlchemy-2.0.36-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 46.2 MB/s eta 0:00:00
Downloading ulid_transform-1.0.2-cp312-cp312-manylinux_2_36_x86_64.whl (170 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.1/170.1 kB 13.2 MB/s eta 0:00:00
Downloading uv-0.5.8-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (14.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.8/14.8 MB 58.2 MB/s eta 0:00:00
Downloading voluptuous-0.15.2-py3-none-any.whl (31 kB)
Downloading voluptuous_openapi-0.0.5-py3-none-any.whl (8.6 kB)
Downloading voluptuous_serialize-2.6.0-py3-none-any.whl (6.8 kB)
Downloading webrtc_models-0.3.0-py3-none-any.whl (7.5 kB)
Downloading yarl-1.18.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (336 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 336.9/336.9 kB 16.0 MB/s eta 0:00:00
Downloading acme-3.0.1-py3-none-any.whl (95 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.9/95.9 kB 5.3 MB/s eta 0:00:00
Downloading httpcore-1.0.7-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.6/78.6 kB 4.5 MB/s eta 0:00:00
Downloading pycognito-2024.5.1-py3-none-any.whl (26 kB)
Downloading snitun-0.39.1-py3-none-any.whl (39 kB)
Downloading certifi-2024.12.14-py3-none-any.whl (164 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 164.9/164.9 kB 8.6 MB/s eta 0:00:00
Downloading packaging-24.2-py3-none-any.whl (65 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 4.7 MB/s eta 0:00:00
Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Downloading urllib3-1.26.20-py2.py3-none-any.whl (144 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 144.2/144.2 kB 8.8 MB/s eta 0:00:00
Downloading aiohappyeyeballs-2.4.4-py3-none-any.whl (14 kB)
Downloading aiosignal-1.3.2-py2.py3-none-any.whl (7.6 kB)
Downloading cffi-1.17.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (479 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 479.4/479.4 kB 21.1 MB/s eta 0:00:00
Downloading charset_normalizer-3.4.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (145 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 145.3/145.3 kB 8.8 MB/s eta 0:00:00
Downloading frozenlist-1.5.0-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (283 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 283.6/283.6 kB 19.9 MB/s eta 0:00:00
Downloading greenlet-3.1.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (613 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 613.1/613.1 kB 34.2 MB/s eta 0:00:00
Downloading habluetooth-3.6.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 56.9 MB/s eta 0:00:00
Downloading idna-3.10-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.4/70.4 kB 5.2 MB/s eta 0:00:00
Downloading MarkupSafe-3.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (23 kB)
Downloading mashumaro-3.15-py3-none-any.whl (93 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.8/93.8 kB 6.8 MB/s eta 0:00:00
Downloading multidict-6.1.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (131 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.0/131.0 kB 9.2 MB/s eta 0:00:00
Downloading pycares-4.5.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (289 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 289.9/289.9 kB 18.4 MB/s eta 0:00:00
Downloading pytz-2024.2-py2.py3-none-any.whl (508 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 508.0/508.0 kB 29.0 MB/s eta 0:00:00
Downloading text_unidecode-1.3-py2.py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.2/78.2 kB 5.6 MB/s eta 0:00:00
Downloading tzdata-2024.2-py2.py3-none-any.whl (346 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 346.6/346.6 kB 17.6 MB/s eta 0:00:00
Downloading anyio-4.7.0-py3-none-any.whl (93 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.1/93.1 kB 5.6 MB/s eta 0:00:00
Downloading sniffio-1.3.1-py3-none-any.whl (10 kB)
Downloading psutil-6.1.1-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (287 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 287.5/287.5 kB 12.7 MB/s eta 0:00:00
Downloading async_timeout-5.0.1-py3-none-any.whl (6.2 kB)
Downloading bleak-0.22.3-py3-none-any.whl (142 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 142.7/142.7 kB 10.7 MB/s eta 0:00:00
Downloading bleak_retry_connector-3.6.0-py3-none-any.whl (15 kB)
Downloading bluetooth_adapters-0.20.2-py3-none-any.whl (19 kB)
Downloading bluetooth_auto_recovery-1.4.2-py3-none-any.whl (10 kB)
Downloading bluetooth_data_tools-1.20.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (882 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 882.4/882.4 kB 36.5 MB/s eta 0:00:00
Downloading boto3-1.35.92-py3-none-any.whl (139 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.2/139.2 kB 8.6 MB/s eta 0:00:00
Downloading envs-1.4-py3-none-any.whl (10 kB)
Downloading h11-0.14.0-py3-none-any.whl (58 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 4.0 MB/s eta 0:00:00
Downloading josepy-1.14.0-py3-none-any.whl (32 kB)
Downloading pycparser-2.22-py3-none-any.whl (117 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.6/117.6 kB 7.1 MB/s eta 0:00:00
Downloading pyRFC3339-2.0.1-py3-none-any.whl (5.8 kB)
Downloading aiooui-0.1.7-py3-none-any.whl (379 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 380.0/380.0 kB 20.6 MB/s eta 0:00:00
Downloading botocore-1.35.92-py3-none-any.whl (13.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.3/13.3 MB 61.3 MB/s eta 0:00:00
Downloading btsocket-0.3.0-py2.py3-none-any.whl (14 kB)
Downloading dbus_fast-2.24.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 60.9 MB/s eta 0:00:00
Downloading jmespath-1.0.1-py3-none-any.whl (20 kB)
Downloading s3transfer-0.10.4-py3-none-any.whl (83 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.2/83.2 kB 4.9 MB/s eta 0:00:00
Downloading uart_devices-0.1.0-py3-none-any.whl (4.8 kB)
Downloading usb_devices-0.4.5-py3-none-any.whl (5.3 kB)
Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 229.9/229.9 kB 12.3 MB/s eta 0:00:00
Building wheels for collected packages: fnvhash, PyRIC
  Building wheel for fnvhash (setup.py) ... done
  Created wheel for fnvhash: filename=fnvhash-0.1.0-py3-none-any.whl size=2149 sha256=1b249de2a036ade5a7c7a68c39fa9fb1bcb6d9577515e2c4961d352cccc6eedf
  Stored in directory: /root/.cache/pip/wheels/f3/f2/c9/9d2b575fa41b9c1f8b35131e1db072490bc6ff034ceb66eaca
  Building wheel for PyRIC (setup.py) ... done
  Created wheel for PyRIC: filename=PyRIC-0.1.6.3-py2.py3-none-any.whl size=407893 sha256=ce94bce06264de0a550130e5070b09c2e4090eed093391feb310b7fd405f2eaa
  Stored in directory: /root/.cache/pip/wheels/71/5f/b2/33e36e10ea0e6b0dda30e364900611b0d428c72f9be83c3e38
Successfully built fnvhash PyRIC
Installing collected packages: text-unidecode, pytz, PyRIC, pyrfc3339, ifaddr, fnvhash, ciso8601, btsocket, voluptuous, uv, usb-devices, urllib3, ulid-transform, uart-devices, tzdata, typing-extensions, sniffio, PyYAML, python-slugify, python-dateutil, PyJWT, pycparser, psutil, propcache, Pillow, packaging, orjson, multidict, MarkupSafe, lru-dict, jmespath, idna, h11, greenlet, frozenlist, fnv-hash-fast, envs, dbus-fast, cronsim, charset-normalizer, certifi, bcrypt, awesomeversion, attrs, atomicwrites-homeassistant, async-timeout, async-interrupt, astral, aiooui, aiohappyeyeballs, yarl, voluptuous-serialize, voluptuous-openapi, SQLAlchemy, requests, psutil-home-assistant, mashumaro, Jinja2, httpcore, cffi, botocore, bleak, anyio, aiozoneinfo, aiosignal, webrtc-models, s3transfer, pycares, httpx, cryptography, bluetooth-adapters, aiohttp, snitun, securetar, pyOpenSSL, boto3, bluetooth-data-tools, bluetooth-auto-recovery, bleak-retry-connector, aiohttp-fast-zlib, aiohttp-cors, aiohasupervisor, aiodns, pycognito, josepy, habluetooth, home-assistant-bluetooth, acme, hass-nabucasa, homeassistant
  Attempting uninstall: uv
    Found existing installation: uv 0.5.14
    Uninstalling uv-0.5.14:
      Successfully uninstalled uv-0.5.14
  Attempting uninstall: PyYAML
    Found existing installation: PyYAML 6.0.1
ERROR: Cannot uninstall PyYAML 6.0.1, RECORD file not found. Hint: The package was installed by debian.
```

**Comment by roby9115** [comment]
Hi,
the problem is still present. I think is releated at the pythono version used in venv, that is python 3.12.

Also, on the home assistant page is reported:

**Troubleshooting**: If you do not see the above version of Home Assistant package in your environment, make sure you have the correct Python version installed, as defined under the [Prerequisites](https://www.home-assistant.io/installation/linux#prerequisites).
