### ISSUE TITLE
pf2etools cleanup failure

### ISSUE THREAD

**Issue by BrianBenninger** [community-scripts/ProxmoxVE#1245]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

pf2etools

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/pf2etools.sh)"

### 📝 Provide a clear and concise description of the issue.

error in the cleanup. Can't remove a zip file.

### ⚙️ What settings are you using?

- [X] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

just run the script.

### ❌ Paste the full error output (if available).

  ✔️  Created Service
 ⠋rm: cannot remove 'v0.8.13.zip': No such file or directory

[ERROR] in line 68: exit code 0: while executing command rm "${RELEASE}.zip"

**Comment by MickLesk** [comment]
Fixed

**Comment by BrianBenninger** [comment]
Still receiving the issue when I run a new install.

![image](https://github.com/user-attachments/assets/f55bb281-ccce-4be0-ae71-5170ae930849)

**Comment by MickLesk** [comment]
Old Script. GitHub need Sometime Up to 10min for refresj
