### ISSUE TITLE
Photoprism defaults result in configuration errors.

### ISSUE THREAD

**Issue by jcgillespie** [community-scripts/ProxmoxVE#1621]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

PhotoPrism LXC

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/photoprism.sh)"

### 📝 Provide a clear and concise description of the issue.

Running the default script for PhotoPrism results in a configuration setup that has an error.
This means you can't add users from the CLI (required unless you have a subscription that unlocks the GUI), or use the CLI to manage the system.

### ⚙️ What settings are you using?

- [x] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

1. Run the default settings install of the script.
2. When complete, go to the lxc shell and type a photoprism command e.g. `photoprism index` or `photoprism passwd admin`

### ❌ Paste the full error output (if available).

```
ERRO[2025-01-20T12:53:55-06:00] config: invalid originals path, check configuration and permissions 
```

### 🖼️ Additional context (optional).

Suspect this is related to [this issue](https://github.com/tteck/Proxmox/issues/3978#issuecomment-2439595976)

Screenshot of new install first command
![Image](https://github.com/user-attachments/assets/e1c0f2be-cca3-4b3c-9d84-93e84b5ee505)

Below is the output of the `photoprism config` command
```
root@photoprism:~# photoprism config

GLOBAL CONFIG OPTIONS

|-------------------------|---------------------------------------------------------------------------------------------|
|          Name           |                                            Value                                            |
|-------------------------|---------------------------------------------------------------------------------------------|
| auth-mode               | password                                                                                    |
| admin-user              | admin                                                                                       |
| admin-password          |                                                                                             |
| password-length         |                                                                                           8 |
| password-reset-uri      |                                                                                             |
| register-uri            |                                                                                             |
| login-uri               | /library/login                                                                              |
| session-maxage          |                                                                                     1209600 |
| session-timeout         |                                                                                      604800 |
| session-cache           |                                                                                         900 |
| log-level               | info                                                                                        |
| debug                   | false                                                                                       |
| trace                   | false                                                                                       |
| config-path             | /root/.photoprism/storage/config                                                            |
| certificates-path       | /root/.photoprism/storage/config/certificates                                               |
| options-yaml            | /root/.photoprism/storage/config/options.yml                                                |
| defaults-yaml           | /etc/photoprism/defaults.yml                                                                |
| settings-yaml           | /etc/photoprism/settings.yml (defaults)                                                     |
| settings-yaml           | /root/.photoprism/storage/config/settings.yml                                               |
| originals-path          |                                                                                             |
| originals-limit         |                                                                                        1000 |
| resolution-limit        |                                                                                         150 |
| users-path              | users                                                                                       |
| users-originals-path    | users                                                                                       |
| storage-path            | /root/.photoprism/storage                                                                   |
| users-storage-path      | /root/.photoprism/storage/users                                                             |
| import-path             |                                                                                             |
| import-dest             |                                                                                             |
| cache-path              | /root/.photoprism/storage/cache                                                             |
| cmd-cache-path          | /root/.photoprism/storage/cache/cmd                                                         |
| media-cache-path        | /root/.photoprism/storage/cache/media                                                       |
| thumb-cache-path        | /root/.photoprism/storage/cache/thumbnails                                                  |
| temp-path               | /tmp/photoprism_00000000                                                                    |
| assets-path             | /opt/photoprism/assets                                                                      |
| static-path             | /opt/photoprism/assets/static                                                               |
| build-path              | /opt/photoprism/assets/static/build                                                         |
| img-path                | /opt/photoprism/assets/static/img                                                           |
| templates-path          | /opt/photoprism/assets/templates                                                            |
| sidecar-path            | /root/.photoprism/storage/sidecar                                                           |
| sidecar-yaml            | true                                                                                        |
| backup-path             | /root/.photoprism/storage/backup                                                            |
| backup-schedule         | 14 7 * * *                                                                                  |
| backup-retain           |                                                                                           3 |
| backup-database         | true                                                                                        |
| backup-database-path    | /root/.photoprism/storage/backup/sqlite3                                                    |
| backup-albums           | true                                                                                        |
| backup-albums-path      | /root/.photoprism/storage/backup/albums                                                     |
| index-workers           |                                                                                           2 |
| index-schedule          |                                                                                             |
| wakeup-interval         | 15m0s                                                                                       |
| auto-index              |                                                                                         300 |
| auto-import             |                                                                                          -1 |
| read-only               | false                                                                                       |
| experimental            | false                                                                                       |
| disable-settings        | false                                                                                       |
| disable-backups         | false                                                                                       |
| disable-restart         | false                                                                                       |
| disable-webdav          | false                                                                                       |
| disable-places          | false                                                                                       |
| disable-tensorflow      | false                                                                                       |
| disable-faces           | false                                                                                       |
| disable-classification  | false                                                                                       |
| disable-ffmpeg          | false                                                                                       |
| disable-exiftool        | false                                                                                       |
| disable-vips            | false                                                                                       |
| disable-sips            | true                                                                                        |
| disable-darktable       | false                                                                                       |
| disable-rawtherapee     | false                                                                                       |
| disable-imagemagick     | false                                                                                       |
| disable-heifconvert     | false                                                                                       |
| disable-rsvgconvert     | true                                                                                        |
| disable-vectors         | true                                                                                        |
| disable-jpegxl          | true                                                                                        |
| disable-raw             | false                                                                                       |
| raw-presets             | false                                                                                       |
| exif-bruteforce         | false                                                                                       |
| detect-nsfw             | false                                                                                       |
| upload-nsfw             | false                                                                                       |
| tensorflow-version      | 1.15.2                                                                                      |
| tensorflow-model-path   | /opt/photoprism/assets/nasnet                                                               |
| default-locale          | en                                                                                          |
| default-timezone        | UTC                                                                                         |
| default-theme           | default                                                                                     |
| app-name                | PhotoPrism                                                                                  |
| app-mode                | standalone                                                                                  |
| app-icon                | logo                                                                                        |
| app-color               | #000000                                                                                     |
| legal-info              |                                                                                             |
| legal-url               |                                                                                             |
| wallpaper-uri           | /static/img/wallpaper/welcome.jpg                                                           |
| site-url                | http://localhost:2342/                                                                      |
| site-https              | false                                                                                       |
| site-domain             | localhost                                                                                   |
| site-author             |                                                                                             |
| site-title              | PhotoPrism                                                                                  |
| site-caption            | AI-Powered Photos App                                                                       |
| site-description        |                                                                                             |
| site-preview            | https://i.photoprism.app/prism?cover=64&style=centered%20dark&caption=none&title=PhotoPrism |
| cdn-url                 | /                                                                                           |
| cdn-video               | false                                                                                       |
| cors-origin             |                                                                                             |
| cors-headers            | Accept, Accept-Ranges, Content-Disposition, Content-Encoding, Content-Range, Location       |
| cors-methods            | GET, HEAD, OPTIONS                                                                          |
| base-uri                | /                                                                                           |
| api-uri                 | /api/v1                                                                                     |
| static-uri              | /static                                                                                     |
| content-uri             | /api/v1                                                                                     |
| video-uri               | /api/v1                                                                                     |
| https-proxy             |                                                                                             |
| https-proxy-insecure    | false                                                                                       |
| trusted-proxy           | 172.16.0.0/12                                                                               |
| proxy-proto-header      | X-Forwarded-Proto                                                                           |
| proxy-proto-https       | https                                                                                       |
| disable-tls             | true                                                                                        |
| default-tls             | false                                                                                       |
| tls-email               |                                                                                             |
| tls-cert                |                                                                                             |
| tls-key                 |                                                                                             |
| http-mode               | release                                                                                     |
| http-compression        |                                                                                             |
| http-cache-public       | false                                                                                       |
| http-cache-maxage       |                                                                                     2592000 |
| http-video-maxage       |                                                                                       21600 |
| http-host               | 0.0.0.0                                                                                     |
| http-port               |                                                                                        2342 |
| database-driver         | sqlite3                                                                                     |
| database-dsn            | /root/.photoprism/storage/index.db?_busy_timeout=5000                                       |
| database-server         |                                                                                             |
| database-host           |                                                                                             |
| database-port           |                                                                                             |
| database-user           |                                                                                             |
| database-password       |                                                                                             |
| database-timeout        |                                                                                          15 |
| database-conns          |                                                                                          20 |
| database-conns-idle     |                                                                                          10 |
| mariadb-bin             |                                                                                             |
| mariadb-dump-bin        |                                                                                             |
| ffmpeg-bin              | /usr/bin/ffmpeg                                                                             |
| ffmpeg-encoder          | libx264                                                                                     |
| ffmpeg-size             |                                                                                        4096 |
| ffmpeg-bitrate          |                                                                                          50 |
| ffmpeg-map-video        | 0:v:0                                                                                       |
| ffmpeg-map-audio        | 0:a:0?                                                                                      |
| exiftool-bin            | /usr/bin/exiftool                                                                           |
| sips-bin                |                                                                                             |
| sips-exclude            | avif, avifs, thm                                                                            |
| darktable-bin           | /usr/bin/darktable-cli                                                                      |
| darktable-cache-path    |                                                                                             |
| darktable-config-path   |                                                                                             |
| darktable-exclude       | thm                                                                                         |
| rawtherapee-bin         | /usr/bin/rawtherapee-cli                                                                    |
| rawtherapee-exclude     | dng, thm                                                                                    |
| imagemagick-bin         | /usr/bin/convert                                                                            |
| imagemagick-exclude     | heif, heic, heics, avif, avifs, jxl, thm                                                    |
| heifconvert-bin         | /usr/local/heif-convert                                                                     |
| heifconvert-orientation | keep                                                                                        |
| rsvgconvert-bin         |                                                                                             |
| jpegxldecoder-bin       |                                                                                             |
| download-token          | latruosr                                                                                    |
| preview-token           | ********                                                                                    |
| thumb-library           | vips                                                                                        |
| thumb-color             | preserve                                                                                    |
| thumb-filter            | auto                                                                                        |
| thumb-size              |                                                                                        1920 |
| thumb-size-uncached     |                                                                                        7680 |
| thumb-uncached          | false                                                                                       |
| jpeg-quality            |                                                                                          83 |
| jpeg-size               |                                                                                        7680 |
| png-size                |                                                                                        7680 |
| face-size               |                                                                                          50 |
| face-score              |                                                                                    9.000000 |
| face-overlap            |                                                                                          42 |
| face-cluster-size       |                                                                                          80 |
| face-cluster-score      |                                                                                          15 |
| face-cluster-core       |                                                                                           4 |
| face-cluster-dist       |                                                                                    0.640000 |
| face-match-dist         |                                                                                    0.460000 |
| pid-filename            | /root/.photoprism/storage/photoprism.pid                                                    |
| log-filename            | /root/.photoprism/storage/photoprism.log                                                    |
|-------------------------|---------------------------------------------------------------------------------------------|


OPENID CONNECT (OIDC)

|---------------|------------------------------|
|     Name      |            Value             |
|---------------|------------------------------|
| oidc-uri      |                              |
| oidc-client   |                              |
| oidc-secret   |                              |
| oidc-scopes   | openid email profile address |
| oidc-provider | OpenID                       |
| oidc-icon     | /static/img/oidc.svg         |
| oidc-redirect | false                        |
| oidc-register | false                        |
| oidc-username | preferred_username           |
| oidc-role     | guest                        |
| oidc-webdav   | false                        |
| disable-oidc  | false                        |
|---------------|------------------------------|
```

**Comment by MickLesk** [comment]
done for new installs.

**Comment by jcgillespie** [comment]
@MickLesk tried this fresh this morning. The same error appears as before, same steps.

Also, I'm getting a new error early in the script. Doesn't appear to halt the installation, but this didn't happen yesterday. 

```
Command failed with status code 5.
command '/sbin/vgscan --ignorelockingfailure --mknodes' failed: exit code 5
 ⠧environment: line 141: exit: Menu aborted.: numeric argument required
```

Happens after option selection for both default and advanced installs, before the prompt to select a location for the template.

```
  🔍  Verbose Mode: yes
  🚀  Creating a PhotoPrism LXC using the above advanced settings
 ⠼  Command failed with status code 5.
command '/sbin/vgscan --ignorelockingfailure --mknodes' failed: exit code 5
  ✔️  Using local for Template Storage.
  Command failed with status code 5.
command '/sbin/vgscan --ignorelockingfailure --mknodes' failed: exit code 5
  ✔️  Using tank for Container Storage.
```

**Comment by MickLesk** [comment]
thats an issue on your proxmox. i havnt any issues
fix is available since 1h

**Comment by jcgillespie** [comment]
@MickLesk - thanks, there was an issue in the storage.cfg. Cleaned that up and the vgscan message is gone.

The original issue is still present though. The output of config looks the same. the `/opt/photoprism/assets` path is in there, but the rest are still looking in `/root/.photoprism/`

<img width="899" alt="Image" src="https://github.com/user-attachments/assets/f13bbc03-5411-4938-a765-9c75f445987b" />

```
GLOBAL CONFIG OPTIONS

|-------------------------|---------------------------------------------------------------------------------------------|
|          Name           |                                            Value                                            |
|-------------------------|---------------------------------------------------------------------------------------------|
| auth-mode               | password                                                                                    |
| admin-user              | admin                                                                                       |
| admin-password          |                                                                                             |
| password-length         |                                                                                           8 |
| password-reset-uri      |                                                                                             |
| register-uri            |                                                                                             |
| login-uri               | /library/login                                                                              |
| session-maxage          |                                                                                     1209600 |
| session-timeout         |                                                                                      604800 |
| session-cache           |                                                                                         900 |
| log-level               | info                                                                                        |
| debug                   | false                                                                                       |
| trace                   | false                                                                                       |
| config-path             | /root/.photoprism/storage/config                                                            |
| certificates-path       | /root/.photoprism/storage/config/certificates                                               |
| options-yaml            | /root/.photoprism/storage/config/options.yml                                                |
| defaults-yaml           | /etc/photoprism/defaults.yml                                                                |
| settings-yaml           | /etc/photoprism/settings.yml (defaults)                                                     |
| settings-yaml           | /root/.photoprism/storage/config/settings.yml                                               |
| originals-path          |                                                                                             |
| originals-limit         |                                                                                        1000 |
| resolution-limit        |                                                                                         150 |
| users-path              | users                                                                                       |
| users-originals-path    | users                                                                                       |
| storage-path            | /root/.photoprism/storage                                                                   |
| users-storage-path      | /root/.photoprism/storage/users                                                             |
| import-path             |                                                                                             |
| import-dest             |                                                                                             |
| cache-path              | /root/.photoprism/storage/cache                                                             |
| cmd-cache-path          | /root/.photoprism/storage/cache/cmd                                                         |
| media-cache-path        | /root/.photoprism/storage/cache/media                                                       |
| thumb-cache-path        | /root/.photoprism/storage/cache/thumbnails                                                  |
| temp-path               | /tmp/photoprism_00000000                                                                    |
| assets-path             | /opt/photoprism/assets                                                                      |
| static-path             | /opt/photoprism/assets/static                                                               |
| build-path              | /opt/photoprism/assets/static/build                                                         |
| img-path                | /opt/photoprism/assets/static/img                                                           |
| templates-path          | /opt/photoprism/assets/templates                                                            |
| sidecar-path            | /root/.photoprism/storage/sidecar                                                           |
| sidecar-yaml            | true                                                                                        |
| backup-path             | /root/.photoprism/storage/backup                                                            |
| backup-schedule         | 59 20 * * *                                                                                 |
| backup-retain           |                                                                                           3 |
| backup-database         | true                                                                                        |
| backup-database-path    | /root/.photoprism/storage/backup/sqlite3                                                    |
| backup-albums           | true                                                                                        |
| backup-albums-path      | /root/.photoprism/storage/backup/albums                                                     |
| index-workers           |                                                                                           2 |
| index-schedule          |                                                                                             |
| wakeup-interval         | 15m0s                                                                                       |
| auto-index              |                                                                                         300 |
| auto-import             |                                                                                          -1 |
| read-only               | false                                                                                       |
| experimental            | false                                                                                       |
| disable-settings        | false                                                                                       |
| disable-backups         | false                                                                                       |
| disable-restart         | false                                                                                       |
| disable-webdav          | false                                                                                       |
| disable-places          | false                                                                                       |
| disable-tensorflow      | false                                                                                       |
| disable-faces           | false                                                                                       |
| disable-classification  | false                                                                                       |
| disable-ffmpeg          | false                                                                                       |
| disable-exiftool        | false                                                                                       |
| disable-vips            | false                                                                                       |
| disable-sips            | true                                                                                        |
| disable-darktable       | false                                                                                       |
| disable-rawtherapee     | false                                                                                       |
| disable-imagemagick     | false                                                                                       |
| disable-heifconvert     | false                                                                                       |
| disable-rsvgconvert     | true                                                                                        |
| disable-vectors         | true                                                                                        |
| disable-jpegxl          | true                                                                                        |
| disable-raw             | false                                                                                       |
| raw-presets             | false                                                                                       |
| exif-bruteforce         | false                                                                                       |
| detect-nsfw             | false                                                                                       |
| upload-nsfw             | false                                                                                       |
| tensorflow-version      | 1.15.2                                                                                      |
| tensorflow-model-path   | /opt/photoprism/assets/nasnet                                                               |
| default-locale          | en                                                                                          |
| default-timezone        | UTC                                                                                         |
| default-theme           | default                                                                                     |
| app-name                | PhotoPrism                                                                                  |
| app-mode                | standalone                                                                                  |
| app-icon                | logo                                                                                        |
| app-color               | #000000                                                                                     |
| legal-info              |                                                                                             |
| legal-url               |                                                                                             |
| wallpaper-uri           | /static/img/wallpaper/welcome.jpg                                                           |
| site-url                | http://localhost:2342/                                                                      |
| site-https              | false                                                                                       |
| site-domain             | localhost                                                                                   |
| site-author             |                                                                                             |
| site-title              | PhotoPrism                                                                                  |
| site-caption            | AI-Powered Photos App                                                                       |
| site-description        |                                                                                             |
| site-preview            | https://i.photoprism.app/prism?cover=64&style=centered%20dark&caption=none&title=PhotoPrism |
| cdn-url                 | /                                                                                           |
| cdn-video               | false                                                                                       |
| cors-origin             |                                                                                             |
| cors-headers            | Accept, Accept-Ranges, Content-Disposition, Content-Encoding, Content-Range, Location       |
| cors-methods            | GET, HEAD, OPTIONS                                                                          |
| base-uri                | /                                                                                           |
| api-uri                 | /api/v1                                                                                     |
| static-uri              | /static                                                                                     |
| content-uri             | /api/v1                                                                                     |
| video-uri               | /api/v1                                                                                     |
| https-proxy             |                                                                                             |
| https-proxy-insecure    | false                                                                                       |
| trusted-proxy           | 172.16.0.0/12                                                                               |
| proxy-proto-header      | X-Forwarded-Proto                                                                           |
| proxy-proto-https       | https                                                                                       |
| disable-tls             | true                                                                                        |
| default-tls             | false                                                                                       |
| tls-email               |                                                                                             |
| tls-cert                |                                                                                             |
| tls-key                 |                                                                                             |
| http-mode               | release                                                                                     |
| http-compression        |                                                                                             |
| http-cache-public       | false                                                                                       |
| http-cache-maxage       |                                                                                     2592000 |
| http-video-maxage       |                                                                                       21600 |
| http-host               | 0.0.0.0                                                                                     |
| http-port               |                                                                                        2342 |
| database-driver         | sqlite3                                                                                     |
| database-dsn            | /root/.photoprism/storage/index.db?_busy_timeout=5000                                       |
| database-server         |                                                                                             |
| database-host           |                                                                                             |
| database-port           |                                                                                             |
| database-user           |                                                                                             |
| database-password       |                                                                                             |
| database-timeout        |                                                                                          15 |
| database-conns          |                                                                                          20 |
| database-conns-idle     |                                                                                          10 |
| mariadb-bin             |                                                                                             |
| mariadb-dump-bin        |                                                                                             |
| ffmpeg-bin              | /usr/bin/ffmpeg                                                                             |
| ffmpeg-encoder          | libx264                                                                                     |
| ffmpeg-size             |                                                                                        4096 |
| ffmpeg-bitrate          |                                                                                          50 |
| ffmpeg-map-video        | 0:v:0                                                                                       |
| ffmpeg-map-audio        | 0:a:0?                                                                                      |
| exiftool-bin            | /usr/bin/exiftool                                                                           |
| sips-bin                |                                                                                             |
| sips-exclude            | avif, avifs, thm                                                                            |
| darktable-bin           | /usr/bin/darktable-cli                                                                      |
| darktable-cache-path    |                                                                                             |
| darktable-config-path   |                                                                                             |
| darktable-exclude       | thm                                                                                         |
| rawtherapee-bin         | /usr/bin/rawtherapee-cli                                                                    |
| rawtherapee-exclude     | dng, thm                                                                                    |
| imagemagick-bin         | /usr/bin/convert                                                                            |
| imagemagick-exclude     | heif, heic, heics, avif, avifs, jxl, thm                                                    |
| heifconvert-bin         | /usr/local/heif-dec                                                                         |
| heifconvert-orientation | keep                                                                                        |
| rsvgconvert-bin         |                                                                                             |
| jpegxldecoder-bin       |                                                                                             |
| download-token          | fhcy5nmi                                                                                    |
| preview-token           | ********                                                                                    |
| thumb-library           | vips                                                                                        |
| thumb-color             | preserve                                                                                    |
| thumb-filter            | auto                                                                                        |
| thumb-size              |                                                                                        1920 |
| thumb-size-uncached     |                                                                                        7680 |
| thumb-uncached          | false                                                                                       |
| jpeg-quality            |                                                                                          83 |
| jpeg-size               |                                                                                        7680 |
| png-size                |                                                                                        7680 |
| face-size               |                                                                                          50 |
| face-score              |                                                                                    9.000000 |
| face-overlap            |                                                                                          42 |
| face-cluster-size       |                                                                                          80 |
| face-cluster-score      |                                                                                          15 |
| face-cluster-core       |                                                                                           4 |
| face-cluster-dist       |                                                                                    0.640000 |
| face-match-dist         |                                                                                    0.460000 |
| pid-filename            | /root/.photoprism/storage/photoprism.pid                                                    |
| log-filename            | /root/.photoprism/storage/photoprism.log                                                    |
|-------------------------|---------------------------------------------------------------------------------------------|


OPENID CONNECT (OIDC)

|---------------|------------------------------|
|     Name      |            Value             |
|---------------|------------------------------|
| oidc-uri      |                              |
| oidc-client   |                              |
| oidc-secret   |                              |
| oidc-scopes   | openid email profile address |
| oidc-provider | OpenID                       |
| oidc-icon     | /static/img/oidc.svg         |
| oidc-redirect | false                        |
| oidc-register | false                        |
| oidc-username | preferred_username           |
| oidc-role     | guest                        |
| oidc-webdav   | false                        |
| disable-oidc  | false                        |
|---------------|------------------------------|
```

**Comment by MickLesk** [comment]
cant reproduce this. for me it worked all with new install

**Comment by hicsuntdragons** [comment]
> The original issue is still present though. The output of config looks the same. the `/opt/photoprism/assets` path is in there, but the rest are still looking in `/root/.photoprism/`

I had a similar issue - commands find the correct paths when you run then on /otp/photoprism dir, so try running photoprism commands from there instead of the root folder, it might work.
