### ISSUE TITLE
Hoarder script fails to install

### ISSUE THREAD

**Issue by Anti-Apple4life** [community-scripts/ProxmoxVE#1786]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

Hoarder

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/hoarder.sh)"

### 📝 Provide a clear and concise description of the issue.

When I run the install script, it fails with this error
```
 ⠼../.. postinstall: 1 issue found in ./apps/web/package.json:
../.. postinstall:  ⨯ error Similar Tanstack Query dependencies should use the same version. unsync-similar-dependencies
../.. postinstall:   │ {
../.. postinstall:   │   "dependencies": {
../.. postinstall:   ~      "@tanstack/react-query": "^5.24.8",
../.. postinstall:   ~      "@tanstack/react-query-devtools": "^5.21.0"
../.. postinstall:   │   }
../.. postinstall:   │ }
../.. postinstall: 1 issue found (1 ⨯, 0 ⚠️, 0 ✓) across 19 packages in 921.125µs.
../.. postinstall:  Note: use `-i` to ignore dependencies, `-r` to ignore rules, `-p` to ignore packages, and `-f` to autofix fixable issues.
../.. postinstall:  ELIFECYCLE  Command failed with exit code 1.
../.. postinstall: Failed
 ELIFECYCLE  Command failed with exit code 1
```

### ⚙️ What settings are you using?

- [x] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

Install hoarder

### ❌ Paste the full error output (if available).

```
 ⠹! Corepack is about to download https://registry.npmjs.org/pnpm/-/pnpm-9.0.0-alpha.8.tgz
 ⠏Scope: all 20 workspace projects
 ⠸../..                                    |    +3118 ++++++++++++++++++++++++++++++++++++++++++++++++++++++
 ⠦../..                                    | Progress: resolved 0, reused 0, downloaded 1, added 0
 ⠦../..                                    | Progress: resolved 0, reused 0, downloaded 96, added 97
 ⠴../..                                    | Progress: resolved 0, reused 0, downloaded 136, added 154
 ⠴../..                                    | Progress: resolved 0, reused 0, downloaded 151, added 161
 ⠴../..                                    | Progress: resolved 0, reused 0, downloaded 168, added 176
 ⠴../..                                    | Progress: resolved 0, reused 0, downloaded 251, added 297
 ⠴../..                                    | Progress: resolved 0, reused 0, downloaded 376, added 430
 ⠴../..                                    | Progress: resolved 0, reused 0, downloaded 509, added 617
 ⠴../..                                    | Progress: resolved 0, reused 0, downloaded 604, added 720
 ⠼../..                                    | Progress: resolved 0, reused 0, downloaded 693, added 823
 ⠼../..                                    | Progress: resolved 0, reused 0, downloaded 776, added 901
 ⠼../..                                    | Progress: resolved 0, reused 0, downloaded 898, added 1053
 ⠼../..                                    | Progress: resolved 0, reused 0, downloaded 1011, added 1202
 ⠼../..                                    | Progress: resolved 0, reused 0, downloaded 1063, added 1244
 ⠼../..                                    | Progress: resolved 0, reused 0, downloaded 1110, added 1311
 ⠸../..                                    | Progress: resolved 0, reused 0, downloaded 1319, added 1580
 ⠸../..                                    | Progress: resolved 0, reused 0, downloaded 1483, added 1731
 ⠸../..                                    | Progress: resolved 0, reused 0, downloaded 1669, added 1947
 ⠸../..                                    | Progress: resolved 0, reused 0, downloaded 1768, added 2069
 ⠸../..                                    | Progress: resolved 0, reused 0, downloaded 1948, added 2271
 ⠸../..                                    | Progress: resolved 0, reused 0, downloaded 2215, added 2582
 ⠸../..                                    | Progress: resolved 0, reused 0, downloaded 2341, added 2697
 ⠸../..                                    | Progress: resolved 0, reused 0, downloaded 2560, added 2959
 ⠙../..                                    | Progress: resolved 0, reused 0, downloaded 2684, added 3118, done
../../node_modules/@swc/core postinstall$ node postinstall.js
 ⠹../../node_modules/better-sqlite3 install$ prebuild-install || node-gyp rebuild --release
../../node_modules/esbuild postinstall$ node install.js
../../node_modules/puppeteer postinstall$ node install.mjs
../../node_modules/@swc/core postinstall: Done
../../node_modules/canvas install$ node-pre-gyp install --fallback-to-build --update-binary
 ⠸../../node_modules/re2 install$ install-from-cache --artifact build/Release/re2.node --host-var RE2_DOWNLOAD_MIRROR --skip-path-var RE2_DOWNLOAD_SKIP_PATH --skip-ver-var RE2_DOWNLOAD_SKIP_VER || node-gyp -j max rebuild
../../node_modules/esbuild postinstall: Done
../../node_modules/re2 install: Trying https://github.com/uhop/node-re2/releases/download/1.21.4/linux-x64-127.br ...
 ⠼../../node_modules/canvas install: node-pre-gyp info it worked if it ends with ok
../../node_modules/canvas install: node-pre-gyp info using node-pre-gyp@1.0.11
../../node_modules/canvas install: node-pre-gyp info using node@22.13.1 | linux | x64
../../node_modules/core-js-pure postinstall$ node -e "try{require('./postinstall')}catch(e){}"
../../node_modules/core-js-pure postinstall: Done
../../node_modules/canvas install: (node:9335) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
../../node_modules/canvas install: (Use `node --trace-deprecation ...` to show where the warning was created)
../../node_modules/canvas install: node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v127-linux-glibc-x64.tar.gz
 ⠦../../node_modules/puppeteer postinstall: **INFO** Skipping browser download as instructed.
../../node_modules/puppeteer postinstall: Done
../../node_modules/canvas install: node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v127-linux-glibc-x64.tar.gz 
../../node_modules/canvas install: node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and node@22.13.1 (node-v127 ABI, glibc) (falling back to source compile with node-gyp) 
../../node_modules/canvas install: node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v127-linux-glibc-x64.tar.gz 
../../node_modules/canvas install: gyp info it worked if it ends with ok
../../node_modules/canvas install: gyp info using node-gyp@10.0.1
../../node_modules/canvas install: gyp info using node@22.13.1 | linux | x64
../../node_modules/canvas install: gyp info ok 
../../node_modules/core-js postinstall$ node -e "try{require('./postinstall')}catch(e){}"
.../node_modules/postman-code-generators postinstall$ node npm/deepinstall.js
 ⠧../../node_modules/canvas install: gyp info it worked if it ends with ok
../../node_modules/canvas install: gyp info using node-gyp@10.0.1
../../node_modules/canvas install: gyp info using node@22.13.1 | linux | x64
../../node_modules/core-js postinstall: Done
 ⠇../../node_modules/canvas install: gyp info find Python using Python version 3.11.2 found at "/usr/bin/python3"
 ⠏../../node_modules/canvas install: gyp http GET https://nodejs.org/download/release/v22.13.1/node-v22.13.1-headers.tar.gz
 ⠋.../core-utils/node_modules/esbuild postinstall$ node install.js
../../node_modules/better-sqlite3 install: Done
.../core-utils/node_modules/esbuild postinstall: Done
 ⠙../../node_modules/tesseract.js postinstall$ opencollective-postinstall || true
../../node_modules/sharp install$ node install/check
../../node_modules/tesseract.js postinstall: Done
 ⠹.../node_modules/postman-code-generators postinstall: Detected package manager: npm
../../node_modules/sharp install: Done
../../node_modules/canvas install: gyp http 200 https://nodejs.org/download/release/v22.13.1/node-v22.13.1-headers.tar.gz
 ⠸../../node_modules/re2 install: Writing to build/Release/re2.node ...
 ⠼.../node_modules/postman-code-generators postinstall: Detected npm version: 10.9.2
.../node_modules/postman-code-generators postinstall: Running pre-package script
 ⠴.../node_modules/postman-code-generators postinstall: Run successful languages.js saved in lib/assets
.../node_modules/postman-code-generators postinstall: csharp-httpclient: npm install --no-audit --production
 ⠦../../node_modules/re2 install: Done.
../../node_modules/re2 install: Done
 ⠋.../node_modules/postman-code-generators postinstall: up to date in 408ms
.../node_modules/postman-code-generators postinstall: csharp-restsharp: npm install --no-audit --production
 ⠼.../node_modules/postman-code-generators postinstall: up to date in 257ms
.../node_modules/postman-code-generators postinstall: curl: npm install --no-audit --production
../../node_modules/canvas install: gyp http GET https://nodejs.org/download/release/v22.13.1/SHASUMS256.txt
 ⠴../../node_modules/canvas install: gyp http 200 https://nodejs.org/download/release/v22.13.1/SHASUMS256.txt
../../node_modules/canvas install: gyp info spawn /usr/bin/python3
../../node_modules/canvas install: gyp info spawn args [
../../node_modules/canvas install: gyp info spawn args '/root/.cache/node/corepack/v1/pnpm/9.0.0-alpha.8/dist/node_modules/node-gyp/gyp/gyp_main.py',
../../node_modules/canvas install: gyp info spawn args 'binding.gyp',
../../node_modules/canvas install: gyp info spawn args '-f',
../../node_modules/canvas install: gyp info spawn args 'make',
../../node_modules/canvas install: gyp info spawn args '-I',
../../node_modules/canvas install: gyp info spawn args '/opt/hoarder/node_modules/canvas/build/config.gypi',
../../node_modules/canvas install: gyp info spawn args '-I',
../../node_modules/canvas install: gyp info spawn args '/root/.cache/node/corepack/v1/pnpm/9.0.0-alpha.8/dist/node_modules/node-gyp/addon.gypi',
../../node_modules/canvas install: gyp info spawn args '-I',
../../node_modules/canvas install: gyp info spawn args '/root/.cache/node-gyp/22.13.1/include/node/common.gypi',
../../node_modules/canvas install: gyp info spawn args '-Dlibrary=shared_library',
../../node_modules/canvas install: gyp info spawn args '-Dvisibility=default',
../../node_modules/canvas install: gyp info spawn args '-Dnode_root_dir=/root/.cache/node-gyp/22.13.1',
../../node_modules/canvas install: gyp info spawn args '-Dnode_gyp_dir=/root/.cache/node/corepack/v1/pnpm/9.0.0-alpha.8/dist/node_modules/node-gyp',
../../node_modules/canvas install: gyp info spawn args '-Dnode_lib_file=/root/.cache/node-gyp/22.13.1/<(target_arch)/node.lib',
../../node_modules/canvas install: gyp info spawn args '-Dmodule_root_dir=/opt/hoarder/node_modules/canvas',
../../node_modules/canvas install: gyp info spawn args '-Dnode_engine=v8',
../../node_modules/canvas install: gyp info spawn args '--depth=.',
../../node_modules/canvas install: gyp info spawn args '--no-parallel',
../../node_modules/canvas install: gyp info spawn args '--generator-output',
../../node_modules/canvas install: gyp info spawn args 'build',
../../node_modules/canvas install: gyp info spawn args '-Goutput_dir=.'
../../node_modules/canvas install: gyp info spawn args ]
 ⠦.../node_modules/postman-code-generators postinstall: up to date in 184ms
.../node_modules/postman-code-generators postinstall: dart-dio: npm install --no-audit --production
../../node_modules/canvas install: /bin/sh: 1: pkg-config: not found
../../node_modules/canvas install: gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
../../node_modules/canvas install: gyp ERR! configure error 
../../node_modules/canvas install: gyp ERR! stack Error: `gyp` failed with exit code: 1
../../node_modules/canvas install: gyp ERR! stack at ChildProcess.<anonymous> (/root/.cache/node/corepack/v1/pnpm/9.0.0-alpha.8/dist/node_modules/node-gyp/lib/configure.js:271:18)
../../node_modules/canvas install: gyp ERR! stack at ChildProcess.emit (node:events:524:28)
../../node_modules/canvas install: gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:293:12)
../../node_modules/canvas install: gyp ERR! System Linux 6.8.12-7-pve
../../node_modules/canvas install: gyp ERR! command "/usr/bin/node" "/root/.cache/node/corepack/v1/pnpm/9.0.0-alpha.8/dist/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--update-binary" "--module=/opt/hoarder/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/opt/hoarder/node_modules/canvas/build/Release" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v127"
../../node_modules/canvas install: gyp ERR! cwd /opt/hoarder/node_modules/canvas
../../node_modules/canvas install: gyp ERR! node -v v22.13.1
../../node_modules/canvas install: gyp ERR! node-gyp -v v10.0.1
../../node_modules/canvas install: gyp ERR! not ok 
 ⠧../../node_modules/canvas install: node-pre-gyp ERR! build error 
../../node_modules/canvas install: node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /root/.cache/node/corepack/v1/pnpm/9.0.0-alpha.8/dist/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/opt/hoarder/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/opt/hoarder/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v127' (1)
../../node_modules/canvas install: node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/opt/hoarder/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
../../node_modules/canvas install: node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:524:28)
../../node_modules/canvas install: node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1101:16)
../../node_modules/canvas install: node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:304:5)
../../node_modules/canvas install: node-pre-gyp ERR! System Linux 6.8.12-7-pve
../../node_modules/canvas install: node-pre-gyp ERR! command "/usr/bin/node" "/opt/hoarder/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
../../node_modules/canvas install: node-pre-gyp ERR! cwd /opt/hoarder/node_modules/canvas
../../node_modules/canvas install: node-pre-gyp ERR! node -v v22.13.1
../../node_modules/canvas install: node-pre-gyp ERR! node-pre-gyp -v v1.0.11
../../node_modules/canvas install: node-pre-gyp ERR! not ok 
../../node_modules/canvas install: Failed to execute '/usr/bin/node /root/.cache/node/corepack/v1/pnpm/9.0.0-alpha.8/dist/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/opt/hoarder/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/opt/hoarder/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v127' (1)
../../node_modules/canvas install: Failed
 ⠹.../node_modules/postman-code-generators postinstall: added 1 package in 481ms
.../node_modules/postman-code-generators postinstall: dart-http: npm install --no-audit --production
 ⠼.../node_modules/postman-code-generators postinstall: up to date in 165ms
.../node_modules/postman-code-generators postinstall: golang: npm install --no-audit --production
 ⠦.../node_modules/postman-code-generators postinstall: up to date in 165ms
.../node_modules/postman-code-generators postinstall: http: npm install --no-audit --production
 ⠦.../node_modules/postman-code-generators postinstall: added 18 packages in 2s
.../node_modules/postman-code-generators postinstall: java-okhttp: npm install --no-audit --production
 ⠇.../node_modules/postman-code-generators postinstall: up to date in 163ms
.../node_modules/postman-code-generators postinstall: java-unirest: npm install --no-audit --production
 ⠋.../node_modules/postman-code-generators postinstall: up to date in 166ms
.../node_modules/postman-code-generators postinstall: js-fetch: npm install --no-audit --production
 ⠏.../node_modules/postman-code-generators postinstall: up to date in 766ms
.../node_modules/postman-code-generators postinstall: js-jquery: npm install --no-audit --production
 ⠙.../node_modules/postman-code-generators postinstall: up to date in 165ms
.../node_modules/postman-code-generators postinstall: js-xhr: npm install --no-audit --production
 ⠴.../node_modules/postman-code-generators postinstall: up to date in 345ms
.../node_modules/postman-code-generators postinstall: kotlin-okhttp: npm install --no-audit --production
 ⠇.../node_modules/postman-code-generators postinstall: added 1 package in 308ms
.../node_modules/postman-code-generators postinstall: libcurl: npm install --no-audit --production
 ⠙.../node_modules/postman-code-generators postinstall: up to date in 171ms
.../node_modules/postman-code-generators postinstall: nodejs-axios: npm install --no-audit --production
 ⠇.../node_modules/postman-code-generators postinstall: added 1 package in 625ms
.../node_modules/postman-code-generators postinstall: nodejs-native: npm install --no-audit --production
 ⠧.../node_modules/postman-code-generators postinstall: added 18 packages in 833ms
.../node_modules/postman-code-generators postinstall: nodejs-request: npm install --no-audit --production
 ⠋.../node_modules/postman-code-generators postinstall: up to date in 2s
.../node_modules/postman-code-generators postinstall: nodejs-unirest: npm install --no-audit --production
 ⠧.../node_modules/postman-code-generators postinstall: up to date in 654ms
.../node_modules/postman-code-generators postinstall: objective-c: npm install --no-audit --production
 ⠋.../node_modules/postman-code-generators postinstall: up to date in 167ms
.../node_modules/postman-code-generators postinstall: ocaml-cohttp: npm install --no-audit --production
 ⠹.../node_modules/postman-code-generators postinstall: up to date in 167ms
.../node_modules/postman-code-generators postinstall: php-curl: npm install --no-audit --production
 ⠼.../node_modules/postman-code-generators postinstall: up to date in 167ms
.../node_modules/postman-code-generators postinstall: php-guzzle: npm install --no-audit --production
 ⠦.../node_modules/postman-code-generators postinstall: up to date in 166ms
.../node_modules/postman-code-generators postinstall: php-httprequest2: npm install --no-audit --production
 ⠏.../node_modules/postman-code-generators postinstall: up to date in 167ms
.../node_modules/postman-code-generators postinstall: php-pecl-http: npm install --no-audit --production
 ⠙.../node_modules/postman-code-generators postinstall: up to date in 167ms
.../node_modules/postman-code-generators postinstall: powershell-restmethod: npm install --no-audit --production
 ⠋.../node_modules/postman-code-generators postinstall: up to date in 900ms
.../node_modules/postman-code-generators postinstall: python-http.client: npm install --no-audit --production
 ⠏.../node_modules/postman-code-generators postinstall: added 18 packages in 825ms
.../node_modules/postman-code-generators postinstall: python-requests: npm install --no-audit --production
 ⠹.../node_modules/postman-code-generators postinstall: up to date in 205ms
.../node_modules/postman-code-generators postinstall: r-httr: npm install --no-audit --production
 ⠼.../node_modules/postman-code-generators postinstall: up to date in 164ms
.../node_modules/postman-code-generators postinstall: r-rcurl: npm install --no-audit --production
 ⠦.../node_modules/postman-code-generators postinstall: up to date in 164ms
.../node_modules/postman-code-generators postinstall: ruby: npm install --no-audit --production
 ⠏.../node_modules/postman-code-generators postinstall: up to date in 194ms
.../node_modules/postman-code-generators postinstall: rust-reqwest: npm install --no-audit --production
 ⠹.../node_modules/postman-code-generators postinstall: added 1 package in 297ms
.../node_modules/postman-code-generators postinstall: shell-httpie: npm install --no-audit --production
 ⠴.../node_modules/postman-code-generators postinstall: up to date in 165ms
.../node_modules/postman-code-generators postinstall: shell-wget: npm install --no-audit --production
 ⠧.../node_modules/postman-code-generators postinstall: up to date in 165ms
.../node_modules/postman-code-generators postinstall: swift: npm install --no-audit --production
 ⠏.../node_modules/postman-code-generators postinstall: up to date in 166ms
.../node_modules/postman-code-generators postinstall: Done
 ⠋
dependencies:
+ @hoarder/db 0.1.0 <- ../../packages/db
+ @hoarder/shared 0.1.0 <- ../../packages/shared
+ @hoarder/shared-react 0.1.0 <- ../../packages/shared-react
+ @hoarder/trpc 0.1.0 <- ../../packages/trpc

devDependencies:
+ @hoarder/eslint-config 0.2.0 <- ../../tooling/eslint
+ @hoarder/prettier-config 0.1.0 <- ../../tooling/prettier
+ @hoarder/tailwind-config 0.1.0 <- ../../tooling/tailwind
+ @hoarder/tsconfig 0.1.0 <- ../../tooling/typescript

 ⠹../.. postinstall$ pnpm lint:ws
 ⠦../.. postinstall: > hoarder@0.1.0 lint:ws /opt/hoarder
../.. postinstall: > pnpm dlx sherif@latest
 ⠋../.. postinstall: Progress: resolved 1, reused 0, downloaded 0, added 0
 ⠹../.. postinstall: Packages: +2
../.. postinstall: ++
 ⠸../.. postinstall: Progress: resolved 7, reused 0, downloaded 2, added 2, done
 ⠼../.. postinstall: 1 issue found in ./apps/web/package.json:
../.. postinstall:  ⨯ error Similar Tanstack Query dependencies should use the same version. unsync-similar-dependencies
../.. postinstall:   │ {
../.. postinstall:   │   "dependencies": {
../.. postinstall:   ~      "@tanstack/react-query": "^5.24.8",
../.. postinstall:   ~      "@tanstack/react-query-devtools": "^5.21.0"
../.. postinstall:   │   }
../.. postinstall:   │ }
../.. postinstall: 1 issue found (1 ⨯, 0 ⚠️, 0 ✓) across 19 packages in 921.125µs.
../.. postinstall:  Note: use `-i` to ignore dependencies, `-r` to ignore rules, `-p` to ignore packages, and `-f` to autofix fixable issues.
../.. postinstall:  ELIFECYCLE  Command failed with exit code 1.
../.. postinstall: Failed
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by rovili** [comment]
I have exactly the same issue:
`dependencies:
+ @hoarder/db 0.1.0 <- ../../packages/db
+ @hoarder/shared 0.1.0 <- ../../packages/shared
+ @hoarder/shared-react 0.1.0 <- ../../packages/shared-react
+ @hoarder/trpc 0.1.0 <- ../../packages/trpc

devDependencies:
+ @hoarder/eslint-config 0.2.0 <- ../../tooling/eslint
+ @hoarder/prettier-config 0.1.0 <- ../../tooling/prettier
+ @hoarder/tailwind-config 0.1.0 <- ../../tooling/tailwind
+ @hoarder/tsconfig 0.1.0 <- ../../tooling/typescript

 ⠙../.. postinstall$ pnpm lint:ws
 ⠴../.. postinstall: > hoarder@0.1.0 lint:ws /opt/hoarder
../.. postinstall: > pnpm dlx sherif@latest
 ⠏../.. postinstall: Progress: resolved 1, reused 0, downloaded 0, added 0
 ⠋../.. postinstall: Packages: +2
../.. postinstall: ++
 ⠹../.. postinstall: Progress: resolved 7, reused 0, downloaded 2, added 2, done
../.. postinstall: 1 issue found in ./apps/web/package.json:
../.. postinstall:  ⨯ error Similar Tanstack Query dependencies should use the same version. unsync-similar-dependencies
../.. postinstall:   │ {
../.. postinstall:   │   "dependencies": {
../.. postinstall:   ~      "@tanstack/react-query": "^5.24.8",
../.. postinstall:   ~      "@tanstack/react-query-devtools": "^5.21.0"
../.. postinstall:   │   }
../.. postinstall:   │ }
../.. postinstall: 1 issue found (1 ⨯, 0 ⚠️, 0 ✓) across 19 packages in 962.583µs.
../.. postinstall:  Note: use `-i` to ignore dependencies, `-r` to ignore rules, `-p` to ignore packages, and `-f` to autofix fixable issues.
../.. postinstall:  ELIFECYCLE  Command failed with exit code 1.
../.. postinstall: Failed
 ELIFECYCLE  Command failed with exit code 1.
 ⠸
[ERROR] in line 73: exit code 0: while executing command $STD pnpm install --frozen-lockfile
root@PVE-HO01:~# `

**Comment by MickLesk** [comment]
@MohamedBassem Have you changed any deps since the frozen-lockfile crashes? Didn't see anything directly at first glance

**Comment by henrikno** [comment]
I changed this line https://github.com/hoarder-app/hoarder/blob/b2c795ccb562c05a5bc6c5df4b4978a015bb1d5f/apps/web/package.json#L50
to match the react-query version, `^5.24.8` it seems to succeed.
`unsync-similar-dependencies` seems like a new linting rule https://newreleases.io/project/npm/sherif/release/1.2.0 was added 2 days ago.

**Comment by MohamedBassem** [comment]
Thanks for the fix @henrikno, I've merged the PR. I'll pin sherif's version moving forward so that we don't hit such problems again. I'll try to push a hotfix release tonight to unblock people hitting this. Sorry for the inconvenience folks.

**Comment by rovili** [comment]
I still get the same error (5min before this post). I see the commit got merged, do I miss something?

**Comment by MickLesk** [comment]
There is no new release yet.

**Comment by joostvdl** [comment]
I have the following error when installing:

[ERROR] in line 44: exit code 0: while executing command "$@" > /dev/null 2>&1

**Comment by MarvinMynx** [comment]
The next release is every day, with the latest one being 20 hours ago. However, there’s still a new ticket or comment almost every day claiming to have the same issue.

Wouldn't it be wise to clearly state when the next release will be publicly available?

By the way, I'm still experiencing the same issue.

**Comment by MohamedBassem** [comment]
Guys, I haven't got a chance to do the release. So sorry. Will publish one by the weekend.

**Comment by MohamedBassem** [comment]
Guys, I haven't got a chance to do the release. So sorry. Will publish one by the weekend.

**Comment by MarvinMynx** [comment]
> > The next release is every day, with the latest one being 9 hours ago. However, there’s still a new ticket or comment almost every day claiming to have the same issue.
> > Wouldn't it be wise to clearly state when the next release will be publicly available?
> > By the way, I'm still experiencing the same issue.
> 
> Lol, not our releases. its not an script issue. you need to wait for new hoarder version

Ah, okay. Well, that wasn’t very clear before. ^^" Sorry about that!

**Comment by MohamedBassem** [comment]
The hoarder release is now out which should hopefully fix this issue

**Comment by MohamedBassem** [comment]
It seems like we're now hitting a completely different issue (https://github.com/hoarder-app/hoarder/issues/967) caused by our package manager. Will keep you updated, and really sorry for the hassle.

**Comment by MickLesk** [comment]
I reopen this, because we get some new (duplicate) Issues.

**Comment by MohamedBassem** [comment]
# Workaround

If you're seeing an error that looks like this when updating/installing hoarder:

```
throw new Error('Cannot find matching keyid
```

Running:

```
npm install -g corepack@0.31.0
```

And then running the update/install script again should solve the issue.

**Comment by MohamedBassem** [comment]
@Aloe-recite I'll need more logs around the error to be able to debug it

**Comment by MickLesk** [comment]
> I just tried but got the “old” error:
> [ERROR] in line 44: exit code 0: while executing command "$@" > /dev/null 2>&1


Execute the Script Part of Update manually for full Log (without >dev/null parts)

**Comment by BasDL91** [comment]
same error when installing.
Workaround didnt work.

```
Error: Cannot find matching keyid: {"signatures":[{"sig":"MEQCIHGqHbvc2zImUPEPFpT4grh6rMYslel+lAjFArx8+RUdAiBfnJA+bgmUvO5Lctfkq+46KKDQdx/8RhLPge3pA+EdHA==","keyid":"SHA256:DhQ8wR5APBvFHLF/+Tc+AYvPOdTpcIDqOhxsBHRwC7U"}],"keys":[{"expires":null,"keyid":"SHA256:jl3bwswu80PjjokCgh0o2w5c2U4LhQAE57gj9cz1kzA","keytype":"ecdsa-sha2-nistp256","scheme":"ecdsa-sha2-nistp256","key":"MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE1Olb3zMAFFxXKHiIkQO5cJ3Yhl5i6UPp+IhuteBJbuHcA5UogKo0EWtlWwW6KSaKoTNEYL7JlCQiVnkhBktUgg=="}]}
    at verifySignature (/usr/lib/node_modules/corepack/dist/lib/corepack.cjs:21535:47)
    at fetchLatestStableVersion (/usr/lib/node_modules/corepack/dist/lib/corepack.cjs:21553:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async fetchLatestStableVersion2 (/usr/lib/node_modules/corepack/dist/lib/corepack.cjs:21672:14)
    at async Engine.getDefaultVersion (/usr/lib/node_modules/corepack/dist/lib/corepack.cjs:22298:23)
    at async Engine.executePackageManagerRequest (/usr/lib/node_modules/corepack/dist/lib/corepack.cjs:22396:47)
    at async Object.runMain (/usr/lib/node_modules/corepack/dist/lib/corepack.cjs:23102:5)

Node.js v22.13.1

[ERROR] in line 73: exit code 0: while executing command $STD pnpm install --frozen-lockfile
```

**Comment by MohamedBassem** [comment]
@BasDL91 I assume you ran this inside the LXC itself right? Can you run `corepack --version` and share its output to validate?

**Comment by MickLesk** [comment]
Maybe:
npm uninstall -g corepack*
npm install -g corepack@0.31.0
rm -rf ~/.cache/corepack
corepack enable

Then Hit Update.


Otherwise If failed again:
corepack prepare pnpm@latest --activate

**Comment by MohamedBassem** [comment]
@MickLesk I'd highly recommend not to update `pnpm` itself (which is what `corepack prepare pnpm@latest --activate` does). This will invalidate the lockfile and force update all the deps, which is going to be super problematic.

**Comment by MickLesk** [comment]
ah yes, right. You are using a fixed version of pnpm. I have removed the 2nd Part of my comment. Maybe that's the problem too? Maybe people have updated pnpm?

**Comment by MohamedBassem** [comment]
@MickLesk If people updated `pnpm` just running `update` again should wipe + refetch the repo and `corepack` should re-install the correct pnpm version before the installation starts.

**Comment by MickLesk** [comment]
I setup tomorrow an older version of hoarder and debug it on my dev Proxmox. 👍

**Comment by 123mariachi123** [comment]
The recommendation of @MickLesk did not help me. Still having issues. Sorry i am a beginner so i cant really provide logs to you now unless you guide me what to do. 
However, i updated corepack as recommended by @MohamedBassem 
`root@hoarder:~# corepack --version`
`0.31.0`

**Comment by MickLesk** [comment]
Exciting, I'm curious to see what I'll see on my test LXC tomorrow or whether I can solve it.

**Comment by vhsdream** [comment]
> The recommendation of [@MickLesk](https://github.com/MickLesk) did not help me. Still having issues. Sorry i am a beginner so i cant really provide logs to you now unless you guide me what to do. However, i updated corepack as recommended by [@MohamedBassem](https://github.com/MohamedBassem) `root@hoarder:~# corepack --version` `0.31.0`

Yes, installing corepack 0.31.0 will fix this and Hoarder can build successfully. Does this issue also occur when updating? I updated my container today without issue and I confirmed I still have corepack 0.30.0

**Comment by 123mariachi123** [comment]
@vhsdream actually it did not for me as i wrote above.

My steps: 

- login to the hoarder lxc, 
- run "update" -> run into the issue

Then, as recommended by @MickLesk above i removed and re-installed corepack and tried an "update" again. No change. Still same issue

> Exciting, I'm curious to see what I'll see on my test LXC tomorrow or whether I can solve it.

@MickLesk i hope you find something. I am already missing my hoarder 😄  Appreciate your help!

**Comment by vhsdream** [comment]
@123mariachi123 do you have a backup of Hoarder from before you ran the update script? If you do then the PR #1957 should allow you to successfully update.

If you don't have a backup, then consider this a lesson learned I guess; Hoarder is very much in active development and things are going to break. Always a good idea to have backups.

**Comment by 123mariachi123** [comment]
@vhsdream i guess PBS is the most valuable service in my homelab then 😄 . Thanks! I wait until your PR is merged and will try again.

**Comment by divemasterjm** [comment]
i've got the following error after update
  ✔️  Stopped Services
  ✔️  Updated Hoarder to v0.22.0
 ⠋Job for hoarder-workers.service failed because of unavailable resources or another system error.
See "systemctl status hoarder-workers.service" and "journalctl -xeu hoarder-workers.service" for details.
Job for hoarder-web.service failed because of unavailable resources or another system error.
See "systemctl status hoarder-web.service" and "journalctl -xeu hoarder-web.service" for details.

[ERROR] in line 64: exit code 0: while executing command systemctl start hoarder-browser hoarder-workers hoarder-web

**Comment by MickLesk** [comment]
can anyone test it? should be working after merge of https://github.com/community-scripts/ProxmoxVE/pull/1957

My test installation was correctly installed at least once with the new version and my second test installation (older version) was successfully updated.

![Image](https://github.com/user-attachments/assets/3ebc5661-a311-4267-80b3-a36eda8ecac6)

![Image](https://github.com/user-attachments/assets/468903a1-3d28-40c5-99a9-c4a692634975)

**Comment by divemasterjm** [comment]
✔️  Stopped Services
  ✔️  Updated Hoarder to v0.22.0
 ⠋Job for hoarder-workers.service failed because of unavailable resources or another system error.
See "systemctl status hoarder-workers.service" and "journalctl -xeu hoarder-workers.service" for details.
Job for hoarder-web.service failed because of unavailable resources or another system error.
See "systemctl status hoarder-web.service" and "journalctl -xeu hoarder-web.service" for details.

[ERROR] in line 67: exit code 0: while executing command systemctl start hoarder-browser hoarder-workers hoarder-web

**Comment by MarvinMynx** [comment]
> can anyone test it? should be working after merge of [#1957](https://github.com/community-scripts/ProxmoxVE/pull/1957)
> 
> My test installation was correctly installed at least once with the new version and my second test installation (older version) was successfully updated.
> 
> ![Image](https://github.com/user-attachments/assets/3ebc5661-a311-4267-80b3-a36eda8ecac6)
> 
> ![Image](https://github.com/user-attachments/assets/468903a1-3d28-40c5-99a9-c4a692634975)

For me it's working now, too.

**Comment by divemasterjm** [comment]
> i've got the following error after update ✔️ Stopped Services ✔️ Updated Hoarder to v0.22.0 ⠋Job for hoarder-workers.service failed because of unavailable resources or another system error. See "systemctl status hoarder-workers.service" and "journalctl -xeu hoarder-workers.service" for details. Job for hoarder-web.service failed because of unavailable resources or another system error. See "systemctl status hoarder-web.service" and "journalctl -xeu hoarder-web.service" for details.
> 
> [ERROR] in line 64: exit code 0: while executing command systemctl start hoarder-browser hoarder-workers hoarder-web

@MohamedBassem any clue? i've updated flawessly until now

**Comment by joostvdl** [comment]
A new install does work now without any error

**Comment by vhsdream** [comment]
> > i've got the following error after update ✔️ Stopped Services ✔️ Updated Hoarder to v0.22.0 ⠋Job for hoarder-workers.service failed because of unavailable resources or another system error. See "systemctl status hoarder-workers.service" and "journalctl -xeu hoarder-workers.service" for details. Job for hoarder-web.service failed because of unavailable resources or another system error. See "systemctl status hoarder-web.service" and "journalctl -xeu hoarder-web.service" for details.
> > [ERROR] in line 64: exit code 0: while executing command systemctl start hoarder-browser hoarder-workers hoarder-web
> 
> [@MohamedBassem](https://github.com/MohamedBassem) any clue? i've updated flawessly until now

Can you try starting the services one at a time? What are the specs for your LXC? How much disk space is available?

**Comment by BasDL91** [comment]
> can anyone test it? should be working after merge of [#1957](https://github.com/community-scripts/ProxmoxVE/pull/1957)
> 
> My test installation was correctly installed at least once with the new version and my second test installation (older version) was successfully updated.
> 
> ![Image](https://github.com/user-attachments/assets/3ebc5661-a311-4267-80b3-a36eda8ecac6)
> 
> ![Image](https://github.com/user-attachments/assets/468903a1-3d28-40c5-99a9-c4a692634975)

works also for me 👌

**Comment by divemasterjm** [comment]
> journalctl -xeu hoarder-web

A stop job for unit hoarder-web.service has finished.
░░ 
░░ The job identifier is 1144 and the job result is done.
Feb 03 17:38:34 hoarder systemd[1]: hoarder-web.service: Start request repeated too quickly.
Feb 03 17:38:34 hoarder systemd[1]: hoarder-web.service: Failed with result 'resources'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit hoarder-web.service has entered the 'failed' state with result 'resources'.
Feb 03 17:38:34 hoarder systemd[1]: Failed to start hoarder-web.service - Hoarder Web.
░░ Subject: A start job for unit hoarder-web.service has failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A start job for unit hoarder-web.service has finished with a failure.
░░ 
░░ The job identifier is 1144 and the job result is failed.


A stop job for unit hoarder-workers.service has finished.
░░ 
░░ The job identifier is 1084 and the job result is done.
Feb 03 17:38:34 hoarder systemd[1]: hoarder-workers.service: Start request repeated too qui>
Feb 03 17:38:34 hoarder systemd[1]: hoarder-workers.service: Failed with result 'resources'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit hoarder-workers.service has entered the 'failed' state with result 'resources'.
Feb 03 17:38:34 hoarder systemd[1]: Failed to start hoarder-workers.service - Hoarder Worke>
░░ Subject: A start job for unit hoarder-workers.service has failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A start job for unit hoarder-workers.service has finished with a failure.
░░ 
░░ The job identifier is 1084 and the job result is failed.




root@hoarder:/opt/hoarder/apps/web# pnpm start

> @hoarder/web@0.1.0 start /opt/hoarder/apps/web
> next start

  ▲ Next.js 14.2.21
  - Local:        http://localhost:3000

 ✓ Starting...
 ⚠ "next start" does not work with "output: standalone" configuration. Use "node .next/standalone/server.js" instead.
 ✓ Ready in 638ms


> @hoarder/workers@0.1.0 start:prod /opt/hoarder/apps/workers
> tsx index.ts

2025-02-03T16:41:39.343Z info: Workers version: not set
2025-02-03T16:41:39.356Z info: [crawler] Loading adblocker ...
(node:4073) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
2025-02-03T16:41:39.426Z info: Running in browserless mode
2025-02-03T16:41:39.426Z info: Starting crawler worker ...
2025-02-03T16:41:39.426Z info: Starting inference worker ...
2025-02-03T16:41:39.427Z info: Starting search indexing worker ...
2025-02-03T16:41:39.427Z info: Starting tidy assets worker ...
2025-02-03T16:41:39.427Z info: Starting video worker ...
2025-02-03T16:41:39.427Z info: Starting feed worker ...
2025-02-03T16:41:39.427Z info: Starting asset preprocessing worker ...
2025-02-03T16:41:39.427Z info: Starting webhook worker ...

**Comment by divemasterjm** [comment]
> [@divemasterjm](https://github.com/divemasterjm) Can you provide some of the journal output for hoarder-web and hoarder-workers?
> 
> `journalctl -xeu hoarder-web` `journalctl -xeu hoarder-workers`.
> 
> Sometimes that gives nothing usable, so you might want to start each service manually and observe the console output.
> 
> For hoarder-web, first `cd` into /opt/hoarder/apps/web, then run `pnpm start` and provide the output.
> 
> For hoarder-workers, `cd` into opt/hoarder/apps/workers, then run `pnpm start:prod`

i've found he solution, i don't know why but updating removes .env file, i've restored from backup the file and works, actually i don't know if i have to change something new on this file, i only change version

**Comment by Thyr1stor** [comment]
This is what i get

LXC has 4 Cores, 8192MiB Memory, 1024Swap, 18G Disk

-------------------------------------

`Update`

  ✔️  Stopped Services
  ✔️  Updated Hoarder to v0.22.0
 ⠋Job for hoarder-workers.service failed because of unavailable resources or another system error.
See "systemctl status hoarder-workers.service" and "journalctl -xeu hoarder-workers.service" for details.
 ⠙Job for hoarder-web.service failed because of unavailable resources or another system error.
See "systemctl status hoarder-web.service" and "journalctl -xeu hoarder-web.service" for details.

[ERROR] in line 67: exit code 0: while executing command systemctl start hoarder-browser hoarder-workers hoarder-web

-------------------------------------

`journalctl -xeu hoarder-web`

░░ Support: https://www.debian.org/support
░░ 
░░ Automatic restarting of the unit hoarder-web.service has been scheduled, as the result for
░░ the configured Restart= setting for the unit.
Feb 03 17:47:21 hdr-prd-01-1 systemd[1]: Stopped hoarder-web.service - Hoarder Web.
░░ Subject: A stop job for unit hoarder-web.service has finished
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A stop job for unit hoarder-web.service has finished.
░░ 
░░ The job identifier is 604 and the job result is done.
Feb 03 17:47:21 hdr-prd-01-1 systemd[1]: hoarder-web.service: Failed to load environment files: No such file or directory
Feb 03 17:47:21 hdr-prd-01-1 systemd[1]: hoarder-web.service: Failed to run 'start' task: No such file or directory
Feb 03 17:47:21 hdr-prd-01-1 systemd[1]: hoarder-web.service: Failed with result 'resources'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit hoarder-web.service has entered the 'failed' state with result 'resources'.
Feb 03 17:47:21 hdr-prd-01-1 systemd[1]: Failed to start hoarder-web.service - Hoarder Web.
░░ Subject: A start job for unit hoarder-web.service has failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A start job for unit hoarder-web.service has finished with a failure.
░░ 
░░ The job identifier is 604 and the job result is failed.
Feb 03 17:47:21 hdr-prd-01-1 systemd[1]: hoarder-web.service: Scheduled restart job, restart counter is at 5.
░░ Subject: Automatic restarting of a unit has been scheduled
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ Automatic restarting of the unit hoarder-web.service has been scheduled, as the result for
░░ the configured Restart= setting for the unit.
Feb 03 17:47:21 hdr-prd-01-1 systemd[1]: Stopped hoarder-web.service - Hoarder Web.
░░ Subject: A stop job for unit hoarder-web.service has finished
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A stop job for unit hoarder-web.service has finished.
░░ 
░░ The job identifier is 725 and the job result is done.
Feb 03 17:47:21 hdr-prd-01-1 systemd[1]: hoarder-web.service: Start request repeated too quickly.
Feb 03 17:47:21 hdr-prd-01-1 systemd[1]: hoarder-web.service: Failed with result 'resources'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit hoarder-web.service has entered the 'failed' state with result 'resources'.
Feb 03 17:47:21 hdr-prd-01-1 systemd[1]: Failed to start hoarder-web.service - Hoarder Web.
░░ Subject: A start job for unit hoarder-web.service has failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A start job for unit hoarder-web.service has finished with a failure.
░░ 
░░ The job identifier is 725 and the job result is failed.

-------------------------------------

`journalctl -xeu hoarder-workers.service`

░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ Automatic restarting of the unit hoarder-workers.service has been scheduled, as the result for
░░ the configured Restart= setting for the unit.
Feb 03 17:52:06 hdr-prd-01-1 systemd[1]: Stopped hoarder-workers.service - Hoarder Workers.
░░ Subject: A stop job for unit hoarder-workers.service has finished
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A stop job for unit hoarder-workers.service has finished.
░░ 
░░ The job identifier is 1269 and the job result is done.
Feb 03 17:52:06 hdr-prd-01-1 systemd[1]: hoarder-workers.service: Start request repeated too quickly.
Feb 03 17:52:06 hdr-prd-01-1 systemd[1]: hoarder-workers.service: Failed with result 'resources'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit hoarder-workers.service has entered the 'failed' state with result 'resources'.
Feb 03 17:52:06 hdr-prd-01-1 systemd[1]: Failed to start hoarder-workers.service - Hoarder Workers.
░░ Subject: A start job for unit hoarder-workers.service has failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A start job for unit hoarder-workers.service has finished with a failure.
░░ 
░░ The job identifier is 1269 and the job result is failed.
Feb 03 17:52:06 hdr-prd-01-1 systemd[1]: hoarder-workers.service: Start request repeated too quickly.
Feb 03 17:52:06 hdr-prd-01-1 systemd[1]: hoarder-workers.service: Failed with result 'resources'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit hoarder-workers.service has entered the 'failed' state with result 'resources'.
Feb 03 17:52:06 hdr-prd-01-1 systemd[1]: Failed to start hoarder-workers.service - Hoarder Workers.
░░ Subject: A start job for unit hoarder-workers.service has failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A start job for unit hoarder-workers.service has finished with a failure.
░░ 
░░ The job identifier is 1448 and the job result is failed.
Feb 03 17:52:07 hdr-prd-01-1 systemd[1]: hoarder-workers.service: Start request repeated too quickly.
Feb 03 17:52:07 hdr-prd-01-1 systemd[1]: hoarder-workers.service: Failed with result 'resources'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit hoarder-workers.service has entered the 'failed' state with result 'resources'.
Feb 03 17:52:07 hdr-prd-01-1 systemd[1]: Failed to start hoarder-workers.service - Hoarder Workers.
░░ Subject: A start job for unit hoarder-workers.service has failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A start job for unit hoarder-workers.service has finished with a failure.
░░ 
░░ The job identifier is 1509 and the job result is failed.

-------------------------------------

`cd /opt/hoarder/apps/web# pnpm start`

> @hoarder/web@0.1.0 start /opt/hoarder/apps/web
> next start

  ▲ Next.js 14.2.21
  - Local:        http://localhost:3000

 ✓ Starting...
 ⚠ "next start" does not work with "output: standalone" configuration. Use "node .next/standalone/server.js" instead.
 ✓ Ready in 643ms

-------------------------------------

`cd /opt/hoarder/apps/workers# pnpm start:prod`

> @hoarder/workers@0.1.0 start:prod /opt/hoarder/apps/workers
> tsx index.ts

2025-02-03T16:56:12.691Z info: Workers version: not set
2025-02-03T16:56:12.713Z info: [crawler] Loading adblocker ...
(node:452) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
2025-02-03T16:56:13.945Z info: Running in browserless mode
2025-02-03T16:56:13.945Z info: Starting crawler worker ...
2025-02-03T16:56:13.945Z info: Starting inference worker ...
2025-02-03T16:56:13.946Z info: Starting search indexing worker ...
2025-02-03T16:56:13.946Z info: Starting tidy assets worker ...
2025-02-03T16:56:13.946Z info: Starting video worker ...
2025-02-03T16:56:13.947Z info: Starting feed worker ...
2025-02-03T16:56:13.947Z info: Starting asset preprocessing worker ...
2025-02-03T16:56:13.947Z info: Starting webhook worker ...

**Comment by vhsdream** [comment]
> > [@divemasterjm](https://github.com/divemasterjm) Can you provide some of the journal output for hoarder-web and hoarder-workers?
> > `journalctl -xeu hoarder-web` `journalctl -xeu hoarder-workers`.
> > Sometimes that gives nothing usable, so you might want to start each service manually and observe the console output.
> > For hoarder-web, first `cd` into /opt/hoarder/apps/web, then run `pnpm start` and provide the output.
> > For hoarder-workers, `cd` into opt/hoarder/apps/workers, then run `pnpm start:prod`
> 
> i've found he solution, i don't know why but updating removes .env file, i've restored from backup the file and works, actually i don't know if i have to change something new on this file, i only change version

@divemasterjm and @Thyr1stor - what's the location of your Hoarder env file? It's supposed to be in `/etc/hoarder/hoarder.env` and the 'EnvrironmentFile' entry in hoarder-web and hoarder-workers should be set to that path. If your env file is located anywhere else, please move it to there and make sure the filename is as above.

**Comment by divemasterjm** [comment]
my .env file is located in /opt/hoarder, but name is .env as was always, do
i vahe to rename it? also services?

**Comment by Thyr1stor** [comment]
On my LXC there is no diretory `/etc/hoarder/` 
 .env is in `/opt/hoarder/`

**Comment by vhsdream** [comment]
That's weird, there is a check in the update script to move the env file from there if it is in the old location. Run this, then check if it has been moved afterwards:

```shell
if [[ -f /opt/hoarder/.env ]] && [[ ! -f /etc/hoarder/hoarder.env ]]; then
      mkdir -p /etc/hoarder
      mv /opt/hoarder/.env /etc/hoarder/hoarder.env
fi
```
And make sure the 'EnvironmentFile' entry in the web and workers service files has the new location if it doesn't already.

**Comment by MohamedBassem** [comment]
@vhsdream On the phone now, but maybe it was an old version of the script? Maybe ask them to check the backup location that you used to keep the env file in during the update? I assume the script breaking in the middle might have left the file in the backup location without restoring it back?

**Comment by divemasterjm** [comment]
> That's weird, there is a check in the update script to move the env file from there if it is in the old location. Run this, then check if it has been moved afterwards:
> 
> if [[ -f /opt/hoarder/.env ]] && [[ ! -f /etc/hoarder/hoarder.env ]]; then
>       mkdir -p /etc/hoarder
>       mv /opt/hoarder/.env /etc/hoarder/hoarder.env
> fi
> And make sure the 'EnvironmentFile' entry in the web and workers service files has the new location if it doesn't already.

everything was on /opt/hoarder, the script didnt move the file nor create /etc/hoarder.
did it manually, also change system services files to point new location, reload and works

**Comment by Thyr1stor** [comment]
> > That's weird, there is a check in the update script to move the env file from there if it is in the old location. Run this, then check if it has been moved afterwards:
> > if [[ -f /opt/hoarder/.env ]] && [[ ! -f /etc/hoarder/hoarder.env ]]; then
> > mkdir -p /etc/hoarder
> > mv /opt/hoarder/.env /etc/hoarder/hoarder.env
> > fi
> > And make sure the 'EnvironmentFile' entry in the web and workers service files has the new location if it doesn't already.
> 
> everything was on /opt/hoarder, the script didnt move the file nor create /etc/hoarder. did it manually, also change system services files to point new location, reload and works

Can confirm - its now updated and working

**Comment by vhsdream** [comment]
I think this is resolved now, and can be closed.

**Comment by MickLesk** [comment]
read changelog.

Changed
💥 Breaking Changes
Update Hoarder: Improvement .env location (see PR comment for little migration) [@MahrWe](https://github.com/MahrWe) (https://github.com/community-scripts/ProxmoxVE/pull/1325)

**Comment by hjaltij** [comment]
Got it. Thanks.
