### ISSUE TITLE
GoMFT Update Fails

### ISSUE THREAD

**Issue by keywal** [community-scripts/ProxmoxVE#3448]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

GoMFT

### 📂 What was the exact command used to execute the script?

update

### 📝 Provide a clear and concise description of the issue.

GoMFT update fails

### ⚙️ What settings are you using?

- [x] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

Run update within the container - get below error

### ❌ Paste the full error output (if available).

```
   ______      __  _______________
  / ____/___  /  |/  / ____/_  __/
 / / __/ __ \/ /|_/ / /_    / /   
/ /_/ / /_/ / /  / / __/   / /    
\____/\____/_/  /_/_/     /_/     
                                  

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
build-essential is already the newest version (12.9).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
  ✔️   Stopped GoMFT
⠙ Updating GoMFT to 0.2.1(!) templ version check: generator v0.3.857 is newer than templ version v0.3.833 found in go.mod file, consider running `go get -u github.com/a-h/templ` to upgrade
⠼ Updating GoMFT to 0.2.1(✓) Complete [ updates=88 duration=402.469733ms ]
⠏ Updating GoMFT to 0.2.1# github.com/starfleetcptn/gomft/components
components/admin_tools_templ.go:17:6: BackupFile redeclared in this block
        components/admin_database_templ.go:17:6: other declaration of BackupFile
components/admin_tools_templ.go:854:76: backup.ModTime undefined (type BackupFile has no field or method ModTime)

[ERROR] in line 53: exit code 0: while executing command $STD go build -o gomft
```

### 🖼️ Additional context (optional).

running 'update' or the full command is the same.

**Comment by tremor021** [comment]
Ofc, app gets complete redesign and some breaking changes... need to see what they did now

**Comment by tremor021** [comment]
@keywal after the PR merges, please try to update again.

**Comment by keywal** [comment]
Unfortunately not working but a different error at least

`   ______      __  _______________
  / ____/___  /  |/  / ____/_  __/
 / / __/ __ \/ /|_/ / /_    / /   
/ /_/ / /_/ / /  / / __/   / /    
\____/\____/_/  /_/_/     /_/     
                                  

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
build-essential is already the newest version (12.9).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
  ✔️   Stopped GoMFT
⠴ Updating GoMFT to 0.2.3
[ERROR] in line 44: exit code 0: while executing command wget -q "https://github.com/StarFleetCPTN/GoMFT/archive/refs/tags/v${RELEASE}.tar.gz" -O $temp_file`

**Comment by tremor021** [comment]
Awesome, they messed with release naming also.... Fix incoming...

**Comment by tremor021** [comment]
There we go, should be fixed after the merge.

**Comment by noway42** [comment]
thanks for the two fixes, but at least for me it is still not working:
`   ______      __  _______________
  / ____/___  /  |/  / ____/_  __/
 / / __/ __ \/ /|_/ / /_    / /   
/ /_/ / /_/ / /  / / __/   / /    
\____/\____/_/  /_/_/     /_/     
                                  

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
build-essential is already the newest version (12.9).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
  ✔️   Stopped GoMFT
⠏ Updating GoMFT to 0.2.3(!) templ version check: generator v0.3.857 is newer than templ version v0.3.833 found in go.mod file, consider running `go get -u github.com/a-h/templ` to upgrade
⠧ Updating GoMFT to 0.2.3(✓) Complete [ updates=88 duration=803.537554ms ]
⠙ Updating GoMFT to 0.2.3# github.com/starfleetcptn/gomft/components
components/admin_tools_templ.go:17:6: BackupFile redeclared in this block
        components/admin_database_templ.go:17:6: other declaration of BackupFile
components/admin_tools_templ.go:909:76: backup.ModTime undefined (type BackupFile has no field or method ModTime)
⠹ Updating GoMFT to 0.2.3
[ERROR] in line 53: exit code 0: while executing command $STD go build -o gomft`

do you have any idea on this? thanks!

**Comment by tremor021** [comment]
Oh boy... they rewrote the frontend in NodeJS. Script will need a rewrite.

**Comment by tremor021** [comment]
![Image](https://github.com/user-attachments/assets/cddb46f7-ed0e-4417-a0d4-b9b071b73d6f)

Ok, the application is much better looking now.

**Comment by noway42** [comment]
`   ______      __  _______________
  / ____/___  /  |/  / ____/_  __/
 / / __/ __ \/ /|_/ / /_    / /   
/ /_/ / /_/ / /  / / __/   / /    
\____/\____/_/  /_/_/     /_/     
                                  

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
build-essential is already the newest version (12.9).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
  ✔️   Stopped GoMFT
⠼ Updating GoMFT to 0.2.4curl: (22) The requested URL returned error: 404
⠴ Updating GoMFT to 0.2.4
[ERROR] in line 50: exit code 0: while executing command curl -fsSL "https://github.com/StarFleetCPTN/GoMFT/archive/refs/tags/v.${RELEASE}.tar.gz" -o $temp_file
`
it looks like the last change on release naming might have been a typo... I think you might need to revert [#3483](https://github.com/community-scripts/ProxmoxVE/pull/3483).

**Comment by MickLesk** [comment]
last change, otherwise it will be removed, if the developer doesnt use the same release file logic

https://github.com/community-scripts/ProxmoxVE/pull/3537
