### ISSUE TITLE
AdventureLog LXC v0.10.0 Fails to Install

### ISSUE THREAD

**Issue by beinncruachan** [community-scripts/ProxmoxVE#5402]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

AdventureLog

### 📂 What was the exact command used to execute the script?

bash -c "$(curl -fsSL https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/ct/adventurelog.sh)"

### ⚙️ What settings are you using?

- [x] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 📝 Provide a clear and concise description of the issue.

Installation of the AdventureLog LXC container version 0.10.0 stops before completion with the error below.

### 🔄 Steps to reproduce the issue.

1. Paste community script link from website into Shell on Proxmox Cluster Node.
2. Select Default settings
3. Script fails with error below

### ❌ Paste the full error output (if available).

0: line 24: install_node_and_modules: command not found

[ERROR] in line 24: exit code 0: while executing command NODE_VERSION="22" NODE_MODULE="pnpm@latest" install_node_and_modules

[ERROR] in line 1088: exit code 0: while executing command lxc-attach -n "$CTID" -- bash -c "$(curl -fsSL https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/install/"$var_install".sh)" $?

**Comment by MickLesk** [comment]
Fixed, try again in next 10min

**Comment by beinncruachan** [comment]
Just tries setting up the container again but the install still fails. The first error has been fixed but I'm still getting the second error.

✔️   Setup adventurelog (0.10.0)
  ⠏   Installing AdventureLog (Patience)0: line 92: RELEASE: unbound variable

[ERROR] in line 1088: exit code 0: while executing command lxc-attach -n "$CTID" -- bash -c "$(curl -fsSL https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/install/"$var_install".sh)" $?

Thanks you your help.

**Comment by MickLesk** [comment]
Fixed

**Comment by beinncruachan** [comment]
Still won't install. Different error this time:

  ✔️   Customized Container
  ⠋   Cleaning up0: line 149: RELEASE: unbound variable

[ERROR] in line 1088: exit code 0: while executing command lxc-attach -n "$CTID" -- bash -c "$(curl -fsSL https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/install/"$var_install".sh)" $?

Thanks again.

**Comment by MickLesk** [comment]
No its GitHub delay, this is not Part of Script

**Comment by beinncruachan** [comment]
Okay, thanks. I'll try again later and hopefully have better luck.
Thanks again for your help.

**Comment by beinncruachan** [comment]
Can confirm that the container now installs.
Thanks
