### ISSUE TITLE
Joplin error install

### ISSUE THREAD

**Issue by LuCoSiN** [community-scripts/ProxmoxVE#8576]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

Joplin Server LXC

### 📂 What was the exact command used to execute the script?

bash -c "$(curl -fsSL https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/ct/joplin-server.sh)"

### ⚙️ What settings are you using?

- [x] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 📈 Which Proxmox version are you on?

9.0.11

### 📝 Provide a clear and concise description of the issue.

I ran the install command and that error occurred. I haven't done anything else. Just select the default configuration.

### 🔄 Steps to reproduce the issue.

I ran the install command and that error occurred. I haven't done anything else. Just select the default configuration.

### ❌ Paste the full error output (if available).

       __            ___            _____                          
      / /___  ____  / (_)___       / ___/___  ______   _____  _____
 __  / / __ \/ __ \/ / / __ \______\__ \/ _ \/ ___/ | / / _ \/ ___/
/ /_/ / /_/ / /_/ / / / / / /_____/__/ /  __/ /   | |/ /  __/ /    
\____/\____/ .___/_/_/_/ /_/     /____/\___/_/    |___/\___/_/     
          /_/                                                      
  ⚙️  Using Default Settings on node BEELINK (🔍  Verbose)
  🆔  Container ID: 103
  🖥️  Operating System: debian (12)
  📦  Container Type: Unprivileged
  💾  Disk Size: 20 GB
  🧠  CPU Cores: 2
  🛠️  RAM Size: 4096 MiB
  🔍  Verbose Mode: Enabled
  🚀  Creating a Joplin-Server LXC using the above default settings
  
  ✔️   Storage local (Free: 78.3GB  Used: 8.8GB) [Template]
  ✔️   Storage local-lvm (Free: 313.8GB  Used: 16.3GB) [Container]
  ✔️   Template debian-12-standard_12.12-1_amd64.tar.zst [local]
  ✔️   LXC Container 103 was successfully created.
  ✔️   Started LXC Container
   💡   No network in LXC yet (try 1/10) – waiting...
  ✔️   Network in LXC is reachable (ping)
  ✔️   Customized LXC Container
  ✔️   Set up Container OS
  ✔️   Network Connected: 192.168.68.77 
  ✔️   IPv4 Internet Connected
   ✖️   IPv6 Internet Not Connected
  ✔️   Git DNS: github.com:(✔️ ) raw.githubusercontent.com:(✔️ ) api.github.com:(✔️ ) git.community-scripts.org:(✔️ )
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://security.debian.org bookworm-security InRelease
Hit:3 http://deb.debian.org/debian bookworm-updates InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  libssl3 openssl
2 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 3,463 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://security.debian.org bookworm-security/main amd64 libssl3 amd64 3.0.17-1~deb12u3 [2,028 kB]
Get:2 http://security.debian.org bookworm-security/main amd64 openssl amd64 3.0.17-1~deb12u3 [1,434 kB]
Fetched 3,463 kB in 0s (12.1 MB/s) 
apt-listchanges: Reading changelogs...
(Reading database ... 20346 files and directories currently installed.)
Preparing to unpack .../libssl3_3.0.17-1~deb12u3_amd64.deb ...
Unpacking libssl3:amd64 (3.0.17-1~deb12u3) over (3.0.17-1~deb12u2) ...
Preparing to unpack .../openssl_3.0.17-1~deb12u3_amd64.deb ...
Unpacking openssl (3.0.17-1~deb12u3) over (3.0.17-1~deb12u2) ...
Setting up libssl3:amd64 (3.0.17-1~deb12u3) ...
Setting up openssl (3.0.17-1~deb12u3) ...
Processing triggers for man-db (2.11.2-2) ...
Processing triggers for libc-bin (2.36-9+deb12u13) ...
  ✔️   Updated Container OS
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  git-man liberror-perl patch
Suggested packages:
  git-daemon-run | git-daemon-sysvinit git-doc git-email git-gui gitk gitweb git-cvs git-mediawiki git-svn ed diffutils-doc
  python3-braceexpand
The following NEW packages will be installed:
  git git-man liberror-perl patch rsync
0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 9,889 kB of archives.
After this operation, 49.3 MB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bookworm/main amd64 rsync amd64 3.2.7-1+deb12u2 [419 kB]
Get:2 http://deb.debian.org/debian bookworm/main amd64 liberror-perl all 0.17029-2 [29.0 kB]
Get:3 http://deb.debian.org/debian bookworm/main amd64 git-man all 1:2.39.5-0+deb12u2 [2,053 kB]
Get:4 http://deb.debian.org/debian bookworm/main amd64 git amd64 1:2.39.5-0+deb12u2 [7,260 kB]
Get:5 http://deb.debian.org/debian bookworm/main amd64 patch amd64 2.7.6-7 [128 kB]
Fetched 9,889 kB in 0s (49.9 MB/s)
Selecting previously unselected package rsync.
(Reading database ... 20346 files and directories currently installed.)
Preparing to unpack .../rsync_3.2.7-1+deb12u2_amd64.deb ...
Unpacking rsync (3.2.7-1+deb12u2) ...
Selecting previously unselected package liberror-perl.
Preparing to unpack .../liberror-perl_0.17029-2_all.deb ...
Unpacking liberror-perl (0.17029-2) ...
Selecting previously unselected package git-man.
Preparing to unpack .../git-man_1%3a2.39.5-0+deb12u2_all.deb ...
Unpacking git-man (1:2.39.5-0+deb12u2) ...
Selecting previously unselected package git.
Preparing to unpack .../git_1%3a2.39.5-0+deb12u2_amd64.deb ...
Unpacking git (1:2.39.5-0+deb12u2) ...
Selecting previously unselected package patch.
Preparing to unpack .../patch_2.7.6-7_amd64.deb ...
Unpacking patch (2.7.6-7) ...
Setting up liberror-perl (0.17029-2) ...
Setting up patch (2.7.6-7) ...
Setting up git-man (1:2.39.5-0+deb12u2) ...
Setting up rsync (3.2.7-1+deb12u2) ...
rsync.service is a disabled or a static unit, not starting it.
Setting up git (1:2.39.5-0+deb12u2) ...
Processing triggers for man-db (2.11.2-2) ...
  ✔️   Installed Dependencies
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian bookworm-updates InRelease
Hit:3 http://security.debian.org bookworm-security InRelease
Get:4 https://apt.postgresql.org/pub/repos/apt bookworm-pgdg InRelease [107 kB]
Get:5 https://apt.postgresql.org/pub/repos/apt bookworm-pgdg/main arm64 Packages [387 kB]
Get:6 https://apt.postgresql.org/pub/repos/apt bookworm-pgdg/main amd64 Packages [402 kB]
Fetched 896 kB in 1s (1,733 kB/s)                        
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian bookworm-updates InRelease                                  
Hit:3 http://security.debian.org bookworm-security InRelease                                   
Hit:4 https://apt.postgresql.org/pub/repos/apt bookworm-pgdg InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ssl-cert is already the newest version (1.1.2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libcommon-sense-perl libjson-perl libjson-xs-perl libllvm19 libpq5 libsensors-config libsensors5 libtypes-serialiser-perl
  libxslt1.1 libz3-4 postgresql-client-common postgresql-common sysstat
Suggested packages:
  libpq-oauth lm-sensors postgresql-doc-17 isag
The following NEW packages will be installed:
  libcommon-sense-perl libjson-perl libjson-xs-perl libllvm19 libpq5 libsensors-config libsensors5 libtypes-serialiser-perl
  libxslt1.1 libz3-4 postgresql-17 postgresql-client-17 postgresql-client-common postgresql-common sysstat
0 upgraded, 15 newly installed, 0 to remove and 0 not upgraded.
Need to get 53.2 MB of archives.
After this operation, 227 MB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bookworm/main amd64 libjson-perl all 4.10000-1 [87.5 kB]
Get:2 http://security.debian.org bookworm-security/main amd64 libjson-xs-perl amd64 4.040-1~deb12u1 [92.4 kB]
Get:3 http://security.debian.org bookworm-security/main amd64 libxslt1.1 amd64 1.1.35-1+deb12u3 [231 kB]                        
Get:4 http://deb.debian.org/debian bookworm/main amd64 libcommon-sense-perl amd64 3.75-3 [23.0 kB]
Get:5 http://deb.debian.org/debian bookworm/main amd64 libtypes-serialiser-perl all 1.01-1 [12.2 kB]   
Get:6 http://deb.debian.org/debian bookworm/main amd64 libz3-4 amd64 4.8.12-3.1 [7,216 kB]                 
Get:7 https://apt.postgresql.org/pub/repos/apt bookworm-pgdg/main amd64 postgresql-client-common all 285.pgdg12+1 [48.9 kB]
Get:8 https://apt.postgresql.org/pub/repos/apt bookworm-pgdg/main amd64 postgresql-common all 285.pgdg12+1 [126 kB]
Get:9 https://apt.postgresql.org/pub/repos/apt bookworm-pgdg/main amd64 libpq5 amd64 18.0-1.pgdg12+3 [249 kB]
Get:10 https://apt.postgresql.org/pub/repos/apt bookworm-pgdg/main amd64 postgresql-client-17 amd64 17.6-2.pgdg12+1 [2,026 kB]
Get:11 https://apt.postgresql.org/pub/repos/apt bookworm-pgdg/main amd64 postgresql-17 amd64 17.6-2.pgdg12+1 [16.5 MB]
Get:12 http://deb.debian.org/debian bookworm/main amd64 libllvm19 amd64 1:19.1.7-3~deb12u1 [25.9 MB]
Get:13 http://deb.debian.org/debian bookworm/main amd64 libsensors-config all 1:3.6.0-7.1 [14.3 kB]
Get:14 http://deb.debian.org/debian bookworm/main amd64 libsensors5 amd64 1:3.6.0-7.1 [34.2 kB]
Get:15 http://deb.debian.org/debian bookworm/main amd64 sysstat amd64 12.6.1-1 [596 kB]
Fetched 53.2 MB in 3s (18.9 MB/s) 
Preconfiguring packages ...
Selecting previously unselected package libjson-perl.
(Reading database ... 21499 files and directories currently installed.)
Preparing to unpack .../00-libjson-perl_4.10000-1_all.deb ...
Unpacking libjson-perl (4.10000-1) ...
Selecting previously unselected package postgresql-client-common.
Preparing to unpack .../01-postgresql-client-common_285.pgdg12+1_all.deb ...
Unpacking postgresql-client-common (285.pgdg12+1) ...
Selecting previously unselected package postgresql-common.
Preparing to unpack .../02-postgresql-common_285.pgdg12+1_all.deb ...
Adding 'diversion of /usr/bin/pg_config to /usr/bin/pg_config.libpq-dev by postgresql-common'
Unpacking postgresql-common (285.pgdg12+1) ...
Selecting previously unselected package libcommon-sense-perl:amd64.
Preparing to unpack .../03-libcommon-sense-perl_3.75-3_amd64.deb ...
Unpacking libcommon-sense-perl:amd64 (3.75-3) ...
Selecting previously unselected package libtypes-serialiser-perl.
Preparing to unpack .../04-libtypes-serialiser-perl_1.01-1_all.deb ...
Unpacking libtypes-serialiser-perl (1.01-1) ...
Selecting previously unselected package libjson-xs-perl.
Preparing to unpack .../05-libjson-xs-perl_4.040-1~deb12u1_amd64.deb ...
Unpacking libjson-xs-perl (4.040-1~deb12u1) ...
Selecting previously unselected package libz3-4:amd64.
Preparing to unpack .../06-libz3-4_4.8.12-3.1_amd64.deb ...
Unpacking libz3-4:amd64 (4.8.12-3.1) ...
Selecting previously unselected package libllvm19:amd64.
Preparing to unpack .../07-libllvm19_1%3a19.1.7-3~deb12u1_amd64.deb ...
Unpacking libllvm19:amd64 (1:19.1.7-3~deb12u1) ...
Selecting previously unselected package libpq5:amd64.
Preparing to unpack .../08-libpq5_18.0-1.pgdg12+3_amd64.deb ...
Unpacking libpq5:amd64 (18.0-1.pgdg12+3) ...
Selecting previously unselected package libsensors-config.
Preparing to unpack .../09-libsensors-config_1%3a3.6.0-7.1_all.deb ...
Unpacking libsensors-config (1:3.6.0-7.1) ...
Selecting previously unselected package libsensors5:amd64.
Preparing to unpack .../10-libsensors5_1%3a3.6.0-7.1_amd64.deb ...
Unpacking libsensors5:amd64 (1:3.6.0-7.1) ...
Selecting previously unselected package libxslt1.1:amd64.
Preparing to unpack .../11-libxslt1.1_1.1.35-1+deb12u3_amd64.deb ...
Unpacking libxslt1.1:amd64 (1.1.35-1+deb12u3) ...
Selecting previously unselected package postgresql-client-17.
Preparing to unpack .../12-postgresql-client-17_17.6-2.pgdg12+1_amd64.deb ...
Unpacking postgresql-client-17 (17.6-2.pgdg12+1) ...
Selecting previously unselected package postgresql-17.
Preparing to unpack .../13-postgresql-17_17.6-2.pgdg12+1_amd64.deb ...
Unpacking postgresql-17 (17.6-2.pgdg12+1) ...
Selecting previously unselected package sysstat.
Preparing to unpack .../14-sysstat_12.6.1-1_amd64.deb ...
Unpacking sysstat (12.6.1-1) ...
Setting up postgresql-client-common (285.pgdg12+1) ...
Setting up libsensors-config (1:3.6.0-7.1) ...
Setting up libpq5:amd64 (18.0-1.pgdg12+3) ...
Setting up libcommon-sense-perl:amd64 (3.75-3) ...
Setting up libz3-4:amd64 (4.8.12-3.1) ...
Setting up libsensors5:amd64 (1:3.6.0-7.1) ...
Setting up libtypes-serialiser-perl (1.01-1) ...
Setting up libjson-perl (4.10000-1) ...
Setting up libxslt1.1:amd64 (1.1.35-1+deb12u3) ...
Setting up sysstat (12.6.1-1) ...

Creating config file /etc/default/sysstat with new version
update-alternatives: using /usr/bin/sar.sysstat to provide /usr/bin/sar (sar) in auto mode
Created symlink /etc/systemd/system/sysstat.service.wants/sysstat-collect.timer → /lib/systemd/system/sysstat-collect.timer.
Created symlink /etc/systemd/system/sysstat.service.wants/sysstat-summary.timer → /lib/systemd/system/sysstat-summary.timer.
Created symlink /etc/systemd/system/multi-user.target.wants/sysstat.service → /lib/systemd/system/sysstat.service.
Setting up libjson-xs-perl (4.040-1~deb12u1) ...
Setting up libllvm19:amd64 (1:19.1.7-3~deb12u1) ...
Setting up postgresql-client-17 (17.6-2.pgdg12+1) ...
update-alternatives: using /usr/share/postgresql/17/man/man1/psql.1.gz to provide /usr/share/man/man1/psql.1.gz (psql.1.gz) in auto mode
Setting up postgresql-common (285.pgdg12+1) ...

Creating config file /etc/postgresql-common/createcluster.conf with new version
Building PostgreSQL dictionaries from installed myspell/hunspell packages...
Removing obsolete dictionary files:
Created symlink /etc/systemd/system/multi-user.target.wants/postgresql.service → /lib/systemd/system/postgresql.service.
Setting up postgresql-17 (17.6-2.pgdg12+1) ...
Creating new PostgreSQL cluster 17/main ...
/usr/lib/postgresql/17/bin/initdb -D /var/lib/postgresql/17/main --auth-local peer --auth-host scram-sha-256 --no-instructions
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/17/main ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default "max_connections" ... 100
selecting default "shared_buffers" ... 128MB
selecting default time zone ... Europe/Madrid
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok
Processing triggers for man-db (2.11.2-2) ...
Processing triggers for libc-bin (2.36-9+deb12u13) ...
  ✔️   Setup PostgreSQL 17
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package 'nodejs' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libc-ares2 libnode108 node-acorn node-busboy node-cjs-module-lexer node-undici node-xtend nodejs-doc
Suggested packages:
  npm
The following NEW packages will be installed:
  libc-ares2 libnode108 node-acorn node-busboy node-cjs-module-lexer node-undici node-xtend nodejs nodejs-doc
0 upgraded, 9 newly installed, 0 to remove and 0 not upgraded.
Need to get 15.1 MB of archives.
After this operation, 70.0 MB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bookworm/main amd64 libc-ares2 amd64 1.18.1-3 [102 kB]
Get:2 http://deb.debian.org/debian bookworm/main amd64 node-xtend all 4.0.2-3 [3,932 B]
Get:3 http://deb.debian.org/debian bookworm/main amd64 nodejs amd64 18.20.4+dfsg-1~deb12u1 [319 kB]
Get:4 http://deb.debian.org/debian bookworm/main amd64 node-acorn all 8.8.1+ds+~cs25.17.7-2 [128 kB]
Get:5 http://deb.debian.org/debian bookworm/main amd64 node-cjs-module-lexer all 1.2.2+dfsg-5 [30.1 kB]
Get:6 http://deb.debian.org/debian bookworm/main amd64 node-busboy all 1.6.0+~cs2.6.0-2 [16.9 kB]
Get:7 http://deb.debian.org/debian bookworm/main amd64 node-undici all 5.15.0+dfsg1+~cs20.10.9.3-1+deb12u4 [285 kB]
Get:8 http://deb.debian.org/debian bookworm/main amd64 libnode108 amd64 18.20.4+dfsg-1~deb12u1 [10.6 MB]
Get:9 http://deb.debian.org/debian bookworm/main amd64 nodejs-doc all 18.20.4+dfsg-1~deb12u1 [3,579 kB]
Fetched 15.1 MB in 0s (47.8 MB/s)     
Selecting previously unselected package libc-ares2:amd64.
(Reading database ... 23911 files and directories currently installed.)
Preparing to unpack .../0-libc-ares2_1.18.1-3_amd64.deb ...
Unpacking libc-ares2:amd64 (1.18.1-3) ...
Selecting previously unselected package node-xtend.
Preparing to unpack .../1-node-xtend_4.0.2-3_all.deb ...
Unpacking node-xtend (4.0.2-3) ...
Selecting previously unselected package nodejs.
Preparing to unpack .../2-nodejs_18.20.4+dfsg-1~deb12u1_amd64.deb ...
Unpacking nodejs (18.20.4+dfsg-1~deb12u1) ...
Selecting previously unselected package node-acorn.
Preparing to unpack .../3-node-acorn_8.8.1+ds+~cs25.17.7-2_all.deb ...
Unpacking node-acorn (8.8.1+ds+~cs25.17.7-2) ...
Selecting previously unselected package node-cjs-module-lexer.
Preparing to unpack .../4-node-cjs-module-lexer_1.2.2+dfsg-5_all.deb ...
Unpacking node-cjs-module-lexer (1.2.2+dfsg-5) ...
Selecting previously unselected package node-busboy.
Preparing to unpack .../5-node-busboy_1.6.0+~cs2.6.0-2_all.deb ...
Unpacking node-busboy (1.6.0+~cs2.6.0-2) ...
Selecting previously unselected package node-undici.
Preparing to unpack .../6-node-undici_5.15.0+dfsg1+~cs20.10.9.3-1+deb12u4_all.deb ...
Unpacking node-undici (5.15.0+dfsg1+~cs20.10.9.3-1+deb12u4) ...
Selecting previously unselected package libnode108:amd64.
Preparing to unpack .../7-libnode108_18.20.4+dfsg-1~deb12u1_amd64.deb ...
Unpacking libnode108:amd64 (18.20.4+dfsg-1~deb12u1) ...
Selecting previously unselected package nodejs-doc.
Preparing to unpack .../8-nodejs-doc_18.20.4+dfsg-1~deb12u1_all.deb ...
Unpacking nodejs-doc (18.20.4+dfsg-1~deb12u1) ...
Setting up node-cjs-module-lexer (1.2.2+dfsg-5) ...
Setting up libc-ares2:amd64 (1.18.1-3) ...
Setting up nodejs-doc (18.20.4+dfsg-1~deb12u1) ...
Setting up node-xtend (4.0.2-3) ...
Setting up node-busboy (1.6.0+~cs2.6.0-2) ...
Setting up node-undici (5.15.0+dfsg1+~cs20.10.9.3-1+deb12u4) ...
Setting up node-acorn (8.8.1+ds+~cs25.17.7-2) ...
Setting up libnode108:amd64 (18.20.4+dfsg-1~deb12u1) ...
Setting up nodejs (18.20.4+dfsg-1~deb12u1) ...
update-alternatives: using /usr/bin/nodejs to provide /usr/bin/js (js) in auto mode
Processing triggers for man-db (2.11.2-2) ...
Processing triggers for libc-bin (2.36-9+deb12u13) ...
  ✔️   Setup Node.js 22
/dev/fd/63: line 2648: npm: command not found
   ✖️   Failed to install yarn@latest

[ERROR] in line 23: exit code 0: while executing command return 1

[ERROR] in line 1345: exit code 0: while executing command lxc-attach -n "$CTID" -- bash -c "$(curl -fsSL https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/install/${var_install}.sh)"

**Comment by MickLesk** [comment]
fixed.

<img width="570" height="343" alt="Image" src="https://github.com/user-attachments/assets/545b9c16-e10f-4603-8900-8c0e9fcffe0b" />

**Comment by LuCoSiN** [comment]
Still having a problem:

       __            ___            _____                          
      / /___  ____  / (_)___       / ___/___  ______   _____  _____
 __  / / __ \/ __ \/ / / __ \______\__ \/ _ \/ ___/ | / / _ \/ ___/
/ /_/ / /_/ / /_/ / / / / / /_____/__/ /  __/ /   | |/ /  __/ /    
\____/\____/ .___/_/_/_/ /_/     /____/\___/_/    |___/\___/_/     
          /_/                                                      
  ⚙️  Using Default Settings on node BEELINK
  🆔  Container ID: 103
  🖥️  Operating System: debian (12)
  📦  Container Type: Unprivileged
  💾  Disk Size: 20 GB
  🧠  CPU Cores: 2
  🛠️  RAM Size: 4096 MiB
  🚀  Creating a Joplin-Server LXC using the above default settings
  
  ✔️   Storage local (Free: 78.3GB  Used: 8.8GB) [Template]
  ✔️   Storage local-lvm (Free: 313.8GB  Used: 16.3GB) [Container]
  ✔️   Template debian-12-standard_12.12-1_amd64.tar.zst [local]
  ✔️   LXC Container 103 was successfully created.
  ✔️   Started LXC Container
   💡   No network in LXC yet (try 1/10) – waiting...
  ✔️   Network in LXC is reachable (ping)
  ✔️   Customized LXC Container
  ✔️   Set up Container OS
  ✔️   Network Connected: 192.168.68.79 
  ✔️   IPv4 Internet Connected
   ✖️   IPv6 Internet Not Connected
  ✔️   Git DNS: github.com:(✔️ ) raw.githubusercontent.com:(✔️ ) api.github.com:(✔️ ) git.community-scripts.org:(✔️ )
  ✔️   Updated Container OS
  ✔️   Installed Dependencies
  ✔️   Setup PostgreSQL 17
  ✔️   Setup Node.js 22
  ✔️   Installed Node.js modules: yarn@latest,npm@latest,pm2@latest
  ✔️   Set up PostgreSQL Database
  ✔️   Deployed: joplin-server (3.4.12)
⠏ Setting up Joplin Server (Patience)
[ERROR] in line 159: exit code 0: while executing command "$@" > /dev/null 2>&1
⠙ Setting up Joplin Server (Patience)
[ERROR] in line 1345: exit code 0: while executing command lxc-attach -n "$CTID" -- bash -c "$(curl -fsSL https://git.community-scripts.org/community-scripts/ProxmoxVE/raw/branch/main/install/${var_install}.sh)"

**Comment by MickLesk** [comment]
run in verbose and create an new issue, thats another topic.

**Comment by LuCoSiN** [comment]
> run in verbose and create an new issue, thats another topic.

Ok thanks
