### ISSUE TITLE
2fauth Install Script Failing

### ISSUE THREAD

**Issue by joel-christian** [community-scripts/ProxmoxVE#9160]
### ✅ Have you read and understood the above guidelines?

Yes

### 📜 What is the name of the script you are using?

2fauth

### 📂 What was the exact command used to execute the script?

bash -c "$(curl -fsSL https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/ct/2fauth.sh)"

### ⚙️ What settings are you using?

- [ ] Default Settings
- [x] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 13

### 📈 Which Proxmox version are you on?

pve-manager/9.0.11/3bf5476b8a4699e2 (running kernel: 6.14.11-4-pve)

### 📝 Provide a clear and concise description of the issue.

After the script installs MariaDB, I see the following errors
Updating dependencies                                 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires enshrined/svg-sanitize ^0.20.0, found enshrined/svg-sanitize[0.20.0] but these were not loaded, because they are affected by security advisories. To ignore the advisories, add ("PKSA-4g5g-4rkv-myqs") to the audit "ignore" config. To turn the feature off entirely, you can set "block-insecure" to false in your "audit" config.

[ERROR] in line 55: exit code 0: while executing command $STD composer update --no-plugins --no-scripts

[ERROR] in line 1346: exit code 0: while executing command lxc-attach -n "$CTID" -- bash -c "$(curl -fsSL https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/install/${var_install}.sh)"

### 🔄 Steps to reproduce the issue.

Step 1: Log into proxmox shell as root
Step 2: Paste the command: bash -c "$(curl -fsSL https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/ct/2fauth.sh)"
Step 3: The script exits before completing

### ❌ Paste the full error output (if available).

[2fauth.txt](https://github.com/user-attachments/files/23557391/2fauth.txt)

**Comment by MickLesk** [comment]
Should be fixed

**Comment by joel-christian** [comment]
The script install is still failing. Verbose output attached with default settings.

[2fauth-verbose.txt](https://github.com/user-attachments/files/23660962/2fauth-verbose.txt)
