### ISSUE TITLE
ERROR Update LXC TPLINK OMADA Software Controller to Controller 5.15.6.7 Build 20241128140044

### ISSUE THREAD

**Issue by bahaman1971** [community-scripts/ProxmoxVE#944]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

"`update`" in the lxc console

### 📂 What was the exact command used to execute the script?

`latest_url=$(curl -fsSL "https://www.tp-link.com/en/support/download/omada-software-controller/" | grep -o 'https://.*x64.deb' | head -n1)`

### 📝 Provide a clear and concise description of the issue.

There is a new version of the Omada software controller available on the website and is also displayed in the software controller itself. 
![2024-12-20 17_59_47-OmadaControllerProxLXC](https://github.com/user-attachments/assets/22e80e9f-636f-45e7-af0f-16f94e5eed2f)
You normally start the update of the LXC in the corresponding console with the command "`update`"
![2024-12-20 17_58_34-ProxFutroS740 - Proxmox Virtual Environment](https://github.com/user-attachments/assets/b585d602-747b-40c6-b56b-97830754e192)
. Now the script aborts with the corresponding error message.
![2024-12-20 17_59_09-ProxFutroS740 - Proxmox Virtual Environment](https://github.com/user-attachments/assets/a3ec766e-fe1c-4b3a-b41f-863b33f1c035)

### ⚙️ What settings are you using?

- [X] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

log into the console 

run "`update`" , the script stops with the error and the virtual omada softwarecontroler in the lxc isn´t updated

### ❌ Paste the full error output (if available).

`[ERROR] in line 58: exit code 0: while executing command latest_url=$(curl -fsSL "https://www.tp-link.com/en/support/download/omada-software-controller/" | grep -o 'https://.*x64.deb' | head -n1)`
![2024-12-20 17_59_09-ProxFutroS740 - Proxmox Virtual Environment](https://github.com/user-attachments/assets/81bceecd-4dbe-4032-9bc9-64f3150e4f90)

**Comment by MickLesk** [comment]
Fixed since lunch? Thats an old call

**Comment by bahaman1971** [comment]
I knew the "old" topic... I rebooted my node and the server, the error still exists and I entered the entry here immediately after the error I found. And it also affected a "different" line of code. And in the end there is no improvement, so I opened a "new" topic. If this is against the rules, I can happily attach my case to the old one, but it doesn't make any sense because I'm writing in a supposed "cold case" ... and the filelink should be 
`https://static.tp-link.com/upload/software/2024/202412/20241205/omada_v5.15.6.7_linux_x64_20241128140044.deb`

**Comment by MickLesk** [comment]
Install a new LXC and Test again. I cant reproduce

**Comment by bahaman1971** [comment]
the lxc was running over 6 month, it was the "old" script from tteckster (R.I.P) maybe thats why you can´t reproduce ... what a trouble shooting

**Comment by MickLesk** [comment]
Because you Hit Update. You dont have updated the Update command? ^^ its an issue by u. We have an Update Script on website

**Comment by bahaman1971** [comment]
i don´t wanne fight here any more :-) I don't want to fight here any further but on your "new" script page it still says...
[https://community-scripts.github.io/ProxmoxVE/scripts?id=omada](url)
`To Update Omada Controller, run the command below (or type update) in the LXC Console.` and only `update `was the instruction for the tteckster script .. I have set up a new lxc and of course it works now. I hope that there is a simpler solution for all users of the "old" tteckster script...

**Comment by MickLesk** [comment]
https://community-scripts.github.io/ProxmoxVE/scripts?id=update-repo

Is the Solution. Your Update Crawl the old tteck Repo, not this Repo. Understand now?

**Comment by MickLesk** [comment]
We have do the simplest Solution ever ^^ you only need to understand this and execute it.
